/**
 * JASPER Busy Mode Engine
 * Handles automatic replies when user is unavailable:
 * - Configurable schedules, presets, contact rules, priority contacts
 * - AI-generated context-aware smart replies via Gemini
 * - Emergency keyword detection and escalation
 * - Full activity logging
 */

const fs = require('fs');
const path = require('path');

const CONFIG_FILE = path.join(__dirname, 'data', 'busy_config.json');
const CONTACTS_FILE = path.join(__dirname, 'data', 'priority_contacts.json');
const ACTIVITY_LOG_FILE = path.join(__dirname, 'data', 'activity_log.json');

class BusyModeEngine {
  constructor() {
    this._broadcastFn = null;
    this._geminiCallFn = null; // injected async fn(prompt) => string
  }

  setBroadcastFn(fn) { this._broadcastFn = fn; }
  setGeminiCallFn(fn) { this._geminiCallFn = fn; }

  // ─── Config ───────────────────────────────────────────────────────────────

  getConfig() {
    try {
      return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'));
    } catch {
      return this._defaultConfig();
    }
  }

  _defaultConfig() {
    return {
      enabled: false,
      preset: 'drive',
      customReply: "I am currently away from my phone. I'll get back to you soon!",
      presets: {
        drive: "🚗 Drive Mode: I'm currently driving. JASPER AI has recorded your message and I will reply as soon as I park.",
        meeting: "💼 Deep Work Mode: I am currently in a focus meeting. Will review your message shortly.",
        sleep: "🌙 DND Mode: Sleeping right now. Auto-reply generated by JASPER Assistant. Type URGENT for emergencies.",
        custom: "I am currently away from my phone. I'll get back to you soon!"
      },
      schedule: { enabled: false, startTime: '09:00', endTime: '17:00', days: ['mon','tue','wed','thu','fri'] },
      allowedApps: { whatsapp: true, instagram: true, email: false, sms: false },
      contactFilter: 'everyone',
      selectedContacts: [],
      aiRepliesEnabled: false,
      askConfirmationBeforeSend: false,
      emergencyKeyword: 'URGENT',
      mentionAvailability: true,
      identifyAsAI: true
    };
  }

  setConfig(updates) {
    const current = this.getConfig();
    const merged = this._deepMerge(current, updates);
    fs.writeFileSync(CONFIG_FILE, JSON.stringify(merged, null, 2));
    return merged;
  }

  _deepMerge(target, source) {
    const result = { ...target };
    for (const key of Object.keys(source)) {
      if (source[key] !== null && typeof source[key] === 'object' && !Array.isArray(source[key])) {
        result[key] = this._deepMerge(target[key] || {}, source[key]);
      } else {
        result[key] = source[key];
      }
    }
    return result;
  }

  isEnabled() {
    const cfg = this.getConfig();
    if (!cfg.enabled) return false;
    if (cfg.schedule && cfg.schedule.enabled) {
      return this._isWithinSchedule(cfg.schedule);
    }
    return true;
  }

  enable() { return this.setConfig({ enabled: true }); }
  disable() { return this.setConfig({ enabled: false }); }
  toggle() { return this.getConfig().enabled ? this.disable() : this.enable(); }

  _isWithinSchedule(schedule) {
    const now = new Date();
    const dayNames = ['sun','mon','tue','wed','thu','fri','sat'];
    const currentDay = dayNames[now.getDay()];
    if (!schedule.days.includes(currentDay)) return false;

    const [sh, sm] = (schedule.startTime || '00:00').split(':').map(Number);
    const [eh, em] = (schedule.endTime || '23:59').split(':').map(Number);
    const currentMinutes = now.getHours() * 60 + now.getMinutes();
    const startMinutes = sh * 60 + sm;
    const endMinutes = eh * 60 + em;
    return currentMinutes >= startMinutes && currentMinutes <= endMinutes;
  }

  // ─── Priority Contacts ────────────────────────────────────────────────────

  getPriorityContacts() {
    try {
      return JSON.parse(fs.readFileSync(CONTACTS_FILE, 'utf8')).contacts || [];
    } catch {
      return [];
    }
  }

  savePriorityContacts(contacts) {
    fs.writeFileSync(CONTACTS_FILE, JSON.stringify({ contacts }, null, 2));
    return contacts;
  }

  addPriorityContact(contact) {
    const contacts = this.getPriorityContacts();
    const newContact = {
      id: `pc-${Date.now()}`,
      name: contact.name,
      identifiers: contact.identifiers || [contact.name.toLowerCase()],
      priority: contact.priority || 'always_notify',
      customReply: contact.customReply || null,
      notifyHours: contact.notifyHours || null
    };
    contacts.push(newContact);
    this.savePriorityContacts(contacts);
    return newContact;
  }

  deletePriorityContact(id) {
    const contacts = this.getPriorityContacts().filter(c => c.id !== id);
    this.savePriorityContacts(contacts);
    return contacts;
  }

  updatePriorityContact(id, updates) {
    const contacts = this.getPriorityContacts().map(c => c.id === id ? { ...c, ...updates } : c);
    this.savePriorityContacts(contacts);
    return contacts.find(c => c.id === id);
  }

  // ─── Message Classification ───────────────────────────────────────────────

  classifyPriority(sender, message) {
    const cfg = this.getConfig();
    const senderLower = (sender || '').toLowerCase();
    const msgLower = (message || '').toLowerCase();

    // Emergency keyword check
    const emergencyKw = (cfg.emergencyKeyword || 'URGENT').toUpperCase();
    if (message.toUpperCase().includes(emergencyKw)) {
      return { priority: 'high', reason: 'Emergency keyword detected', escalate: true };
    }

    // Priority contact check
    const priorityContacts = this.getPriorityContacts();
    for (const pc of priorityContacts) {
      const matched = (pc.identifiers || []).some(id => senderLower.includes(id.toLowerCase()));
      if (!matched) continue;

      if (pc.priority === 'always_notify') {
        return { priority: 'high', reason: `Priority contact: ${pc.name} (Always Notify)`, escalate: true, contact: pc };
      }
      if (pc.priority === 'notify_during_hours' && pc.notifyHours) {
        if (this._isWithinSchedule({ enabled: true, days: ['sun','mon','tue','wed','thu','fri','sat'], startTime: pc.notifyHours.start, endTime: pc.notifyHours.end })) {
          return { priority: 'high', reason: `Priority contact: ${pc.name} (During hours)`, escalate: true, contact: pc };
        }
      }
    }

    // Urgency keywords
    const urgencyWords = ['urgent', 'emergency', 'help', 'asap', 'immediately', 'critical', 'sos'];
    if (urgencyWords.some(w => msgLower.includes(w))) {
      return { priority: 'medium', reason: 'Urgency keyword in message', escalate: false };
    }

    return { priority: 'low', reason: 'Normal message', escalate: false };
  }

  // ─── Reply Generation ─────────────────────────────────────────────────────

  async generateReply(platform, sender, message, classification) {
    const cfg = this.getConfig();

    // Use contact-specific reply if available
    if (classification.contact && classification.contact.customReply) {
      return classification.contact.customReply;
    }

    // AI-generated smart reply
    if (cfg.aiRepliesEnabled && this._geminiCallFn) {
      try {
        const aiIdentity = cfg.identifyAsAI ? ' (This is an automated reply from JASPER AI Assistant)' : '';
        const prompt = `You are JASPER AI assistant sending an auto-reply on behalf of Jwalant who is currently unavailable (${cfg.preset} mode).
Sender: ${sender}
Their message: "${message}"
Reply in 1-2 sentences. Be polite and concise. Do NOT impersonate Jwalant directly — be clear this is an auto-reply.${aiIdentity}`;
        const aiReply = await this._geminiCallFn(prompt);
        if (aiReply && aiReply.trim()) return aiReply.trim();
      } catch (e) {
        console.error('[BusyMode] AI reply failed:', e.message);
      }
    }

    // Preset reply
    const presets = cfg.presets || {};
    const activePreset = cfg.preset || 'drive';
    return presets[activePreset] || cfg.customReply || "I'm currently unavailable. I'll get back to you soon.";
  }

  // ─── Main Processing ──────────────────────────────────────────────────────

  /**
   * Process an incoming message and determine Jasper's response action
   * @returns { action: 'reply'|'escalate'|'ignore', reply: string|null, classification: object }
   */
  async processIncomingMessage(platform, sender, message) {
    const cfg = this.getConfig();
    const timestamp = new Date();

    // Log receipt
    this.appendActivityLog({
      type: 'message_received',
      icon: '📨',
      platform,
      sender,
      message: message.substring(0, 200),
      timestamp: timestamp.toISOString()
    });

    if (!this.isEnabled()) {
      return { action: 'passthrough', reply: null, classification: null };
    }

    // Check if platform is allowed
    const allowedApps = cfg.allowedApps || {};
    if (!allowedApps[platform]) {
      return { action: 'passthrough', reply: null, classification: null };
    }

    // Classify priority
    const classification = this.classifyPriority(sender, message);

    this.appendActivityLog({
      type: 'message_classified',
      icon: classification.priority === 'high' ? '⚠️' : '🤖',
      text: `Classified message from ${sender} as: ${classification.priority.toUpperCase()} — ${classification.reason}`,
      priority: classification.priority,
      timestamp: new Date().toISOString()
    });

    // Escalate high-priority
    if (classification.escalate) {
      this.appendActivityLog({
        type: 'escalation',
        icon: '🔔',
        text: `ALERT: High-priority message from ${sender} — notifying user immediately`,
        timestamp: new Date().toISOString()
      });

      if (this._broadcastFn) {
        this._broadcastFn({
          type: 'BUSY_MODE_ESCALATION',
          platform,
          sender,
          message,
          classification,
          timestamp: timestamp.toISOString()
        });
      }

      return { action: 'escalate', reply: null, classification };
    }

    // Generate and send reply
    const reply = await this.generateReply(platform, sender, message, classification);

    this.appendActivityLog({
      type: 'auto_reply_sent',
      icon: '💬',
      text: `Sent auto-reply to ${sender} via ${platform}`,
      reply: reply.substring(0, 120),
      timestamp: new Date().toISOString()
    });

    return { action: 'reply', reply, classification };
  }

  // ─── Activity Log ─────────────────────────────────────────────────────────

  appendActivityLog(entry) {
    try {
      let log = { entries: [] };
      if (fs.existsSync(ACTIVITY_LOG_FILE)) {
        log = JSON.parse(fs.readFileSync(ACTIVITY_LOG_FILE, 'utf8'));
      }
      const fullEntry = { id: `al-${Date.now()}-${Math.random().toString(36).slice(2,6)}`, ...entry };
      log.entries.unshift(fullEntry); // newest first
      if (log.entries.length > 500) log.entries = log.entries.slice(0, 500); // cap at 500
      fs.writeFileSync(ACTIVITY_LOG_FILE, JSON.stringify(log, null, 2));

      // Broadcast to client
      if (this._broadcastFn) {
        this._broadcastFn({ type: 'ACTIVITY_LOG_UPDATE', entry: fullEntry });
      }

      return fullEntry;
    } catch (e) {
      console.error('[BusyMode] Log write error:', e.message);
    }
  }

  getActivityLog(limit = 100) {
    try {
      const log = JSON.parse(fs.readFileSync(ACTIVITY_LOG_FILE, 'utf8'));
      return (log.entries || []).slice(0, limit);
    } catch {
      return [];
    }
  }

  clearActivityLog() {
    fs.writeFileSync(ACTIVITY_LOG_FILE, JSON.stringify({ entries: [] }, null, 2));
  }

  // ─── Simulate ─────────────────────────────────────────────────────────────

  async simulateIncomingMessage(platform, sender, message) {
    return this.processIncomingMessage(platform, sender, message);
  }
}

module.exports = new BusyModeEngine();
