const fs = require('fs');
const path = require('path');
const vectorMemory = require('./vectorMemory');

// Target directory & file path for database
const DATA_DIR = path.join(__dirname, 'data');
const DB_FILE = path.join(DATA_DIR, 'jasper.db.json');

// Existing legacy files for automatic seamless migration
const LEGACY_MEMORY = path.join(__dirname, 'memory_store.json');
const LEGACY_ANALYTICS = path.join(__dirname, 'analytics_store.json');
const LEGACY_ACTIONS = path.join(__dirname, 'agentic_actions_store.json');
const LEGACY_TV = path.join(__dirname, 'tv-config.json');

// Ensure data directory exists
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

// Initial Database Schema
const DEFAULT_SCHEMA = {
  version: 1.0,
  lastUpdated: new Date().toISOString(),
  memories: [
    { id: 1, text: 'User prefers concise audio responses', category: 'preference', date: new Date().toISOString() },
    { id: 2, text: 'Default smart home TV is Samsung Frame in Living Room', category: 'device', date: new Date().toISOString() }
  ],
  analytics: {
    conversations: 0,
    voiceCommands: 0,
    imagesGenerated: 0,
    automationRuns: 0,
    connectedDevices: 0,
    startTime: Date.now()
  },
  reservations: [],
  chat_history: [
    {
      id: 1,
      query: 'who is narendra modi',
      response: 'Narendra Damodardas Modi is an Indian politician who has served as the prime minister of India since 2014.',
      timestamp: new Date().toLocaleString()
    }
  ],
  reminders: [
    {
      id: 1,
      title: 'Review System Diagnostics',
      time: '09:00 AM',
      date: 'Today',
      category: 'System',
      completed: false,
      createdAt: new Date().toISOString()
    }
  ],
  automations: [
    {
      id: 'auto-1',
      name: 'Morning Wakeup Routine',
      trigger: 'Voice Command: "Good Morning"',
      action: 'Set Volume 50%, Fetch Weather, Play Music',
      enabled: true,
      createdAt: new Date().toISOString()
    }
  ],
  health_vitals: [],
  social_accounts: {
    instagram: {
      username: '@jwalant',
      password: '',
      sessionCookie: '',
      status: 'configured',
      lastAuthenticated: new Date().toISOString()
    },
    whatsapp: {
      senderNumber: '+91 98200 12345',
      countryCode: '+91',
      status: 'connected',
      lastLinked: new Date().toISOString()
    }
  },
  social_auto_reply: {
    whatsappEnabled: true,
    instagramEnabled: true,
    callAutoDeclineAndMsg: true,
    activePreset: 'drive',
    presets: {
      drive: "🚗 Drive Mode: I'm currently driving. JASPER AI has recorded your message and I will reply as soon as I park.",
      meeting: "💼 Deep Work / Meeting Mode: I am currently in a meeting. Will review your message shortly.",
      sleep: "🌙 DND Mode: Sleeping right now. Auto-reply generated by JASPER Assistant. Type URGENT for emergencies.",
      ai_smart: "🤖 Context-aware AI Smart Responder active via Gemini neural engine.",
      custom: "I am currently away from my phone. I'll get back to you soon!"
    },
    aiSmartPrompt: "Formulate a polite, professional, and friendly 1-2 sentence automated reply on behalf of Jwalant.",
    emergencyKeyword: "URGENT",
    whitelistContacts: ["Mom", "Sarah (Office Boss)"]
  },
  social_contacts: [
    { id: 'c1', name: 'Mom', phone: '+91 98200 12345', ig: '@mom_family', platform: 'whatsapp', lastMessage: '🚗 Drive Mode: I\'m currently driving...', lastTimestamp: '10:42 PM', avatarColor: 'from-pink-500 to-rose-500' },
    { id: 'c2', name: 'Fatih Makes', phone: '+1 555 382 9901', ig: '@fatihmakes', platform: 'instagram', lastMessage: 'Automated test DM sent from Jwalant\'s connected Instagram account!', lastTimestamp: '11:45 PM', avatarColor: 'from-purple-500 to-indigo-500' },
    { id: 'c3', name: 'Sarah (Office Boss)', phone: '+91 98233 45678', ig: '@sarah_lead', platform: 'whatsapp', lastMessage: '💼 Deep Work Mode: I am currently in a meeting.', lastTimestamp: '08:15 PM', avatarColor: 'from-blue-500 to-cyan-500' },
    { id: 'c4', name: 'Alex (Auto Mechanic)', phone: '+91 98222 34567', ig: '@alex_mechanic', platform: 'instagram', lastMessage: 'Car inspection report ready for pickup!', lastTimestamp: 'Yesterday', avatarColor: 'from-amber-500 to-orange-500' },
    { id: 'c5', name: 'Dr. Mehta (Dentist)', phone: '+91 98211 23456', ig: '@mehta_clinic', platform: 'whatsapp', lastMessage: 'Appointment scheduled for Tuesday at 4:00 PM', lastTimestamp: 'Aug 28', avatarColor: 'from-emerald-500 to-teal-500' }
  ],
  social_logs: [
    {
      id: "LOG-01",
      platform: "whatsapp",
      type: "call_auto_reply",
      recipient: "+91 98200 12345",
      recipientName: "Mom",
      incomingTextOrCall: "Incoming WhatsApp Call",
      actionTaken: "Declined Call & Sent WhatsApp Auto-Reply",
      messageSent: "🚗 Drive Mode: I'm currently driving. JASPER AI has recorded your message and I will reply as soon as I park.",
      status: "Delivered",
      timestamp: "10:42 PM"
    },
    {
      id: "LOG-02",
      platform: "instagram",
      type: "msg_auto_reply",
      recipient: "@fatihmakes",
      recipientName: "Fatih Makes",
      incomingTextOrCall: "Hey! Can you send the CAD files?",
      actionTaken: "AI Smart Agent Auto-Replied to Instagram DM",
      messageSent: "Hey Fatih! Jwalant is in deep focus mode right now. He will send over the files as soon as he is back at the workstation!",
      status: "Delivered",
      timestamp: "10:35 PM"
    }
  ],
  settings: {
    theme: 'obsidian-modern',
    serverIp: 'localhost',
    fitbandMac: 'F4:67:F4:16:7C:53',
    pcMac: '74:12:B3:ED:1C:BF'
  },
  finance: {
    accounts: [
      { id: 'acc_1', name: 'Primary Bank Account', type: 'bank', balance: 36000.00, currency: '₹', institution: 'Savings Account', isDefault: true, color: 'from-blue-600 to-indigo-700' },
      { id: 'acc_2', name: 'UPI / Digital Wallet', type: 'wallet', balance: 450.00, currency: '₹', institution: 'UPI (GPay / PhonePe / Paytm)', isDefault: false, color: 'from-purple-600 to-violet-700' }
    ],
    budget: {
      monthlyLimit: 2000.00,
      alertThresholdPercent: 85,
      guardianName: 'Mom',
      guardianPhone: '+91 98200 12345',
      guardianPlatform: 'whatsapp',
      guardianAlertsEnabled: true,
      lastAlertDispatchedAt: null,
      cooldownHours: 24,
      alertsHistory: [
        {
          id: 'ALT-INIT',
          date: new Date(Date.now() - 86400000 * 5).toISOString(),
          type: 'warning',
          message: 'Warning: 85% of monthly pocket money limit reached (₹1,700 / ₹2,000).',
          deliveredTo: 'Mom (+91 98200 12345 via WhatsApp)',
          status: 'Delivered'
        }
      ]
    },
    transactions: [],
    settings: {
      defaultCurrency: '₹',
      privacyMask: false
    }
  }
};

class DatabaseManager {
  constructor() {
    this._saveTimer = null;
    this._pendingSave = false;
    this.data = this.init();

    // Flush pending writes before Node process terminates
    process.on('beforeExit', () => this.flushSync());
  }

  // Load database or initialize with migrations
  init() {
    let dbData = null;

    if (fs.existsSync(DB_FILE)) {
      try {
        const content = fs.readFileSync(DB_FILE, 'utf8');
        dbData = JSON.parse(content);
        console.log('[Database Core] Loaded database from:', DB_FILE);
      } catch (e) {
        console.error('[Database Core] Database file read error, recreating schema:', e.message);
      }
    }

    if (!dbData) {
      dbData = JSON.parse(JSON.stringify(DEFAULT_SCHEMA));
      this.migrateLegacyFiles(dbData);
      this.save(dbData, true);
    } else {
      // Ensure all tables exist in loaded dbData
      for (const key of Object.keys(DEFAULT_SCHEMA)) {
        if (dbData[key] === undefined) {
          dbData[key] = DEFAULT_SCHEMA[key];
        }
      }
    }

    return dbData;
  }

  // Migrate legacy individual JSON files if they exist
  migrateLegacyFiles(dbData) {
    console.log('[Database Core] Checking legacy JSON files for data migration...');
    try {
      if (fs.existsSync(LEGACY_MEMORY)) {
        const mem = JSON.parse(fs.readFileSync(LEGACY_MEMORY, 'utf8'));
        if (mem.memories && Array.isArray(mem.memories)) {
          dbData.memories = mem.memories;
          console.log(`[Database Core] Migrated ${mem.memories.length} legacy memory records.`);
        }
      }
    } catch (e) {}

    try {
      if (fs.existsSync(LEGACY_ANALYTICS)) {
        const ana = JSON.parse(fs.readFileSync(LEGACY_ANALYTICS, 'utf8'));
        dbData.analytics = { ...dbData.analytics, ...ana };
        console.log('[Database Core] Migrated legacy analytics counters.');
      }
    } catch (e) {}

    try {
      if (fs.existsSync(LEGACY_ACTIONS)) {
        const act = JSON.parse(fs.readFileSync(LEGACY_ACTIONS, 'utf8'));
        if (Array.isArray(act)) {
          dbData.reservations = act;
          console.log(`[Database Core] Migrated ${act.length} legacy reservations.`);
        }
      }
    } catch (e) {}

    try {
      if (fs.existsSync(LEGACY_TV)) {
        const tv = JSON.parse(fs.readFileSync(LEGACY_TV, 'utf8'));
        dbData.settings = { ...dbData.settings, tvConfig: tv };
        console.log('[Database Core] Migrated legacy TV config.');
      }
    } catch (e) {}
  }

  // Debounced save: updates memory immediately and batches disk writes
  save(dataToSave = this.data, immediate = false) {
    this.data = dataToSave;
    this._pendingSave = true;

    if (immediate) {
      return this.flushSync();
    }

    if (!this._saveTimer) {
      this._saveTimer = setTimeout(() => {
        this.flushSync();
      }, 1500); // 1.5s debounce batching saves CPU & disk I/O
    }
    return true;
  }

  // Synchronously flush pending updates to disk
  flushSync() {
    if (!this._pendingSave) return true;
    if (this._saveTimer) {
      clearTimeout(this._saveTimer);
      this._saveTimer = null;
    }
    this._pendingSave = false;

    try {
      this.data.lastUpdated = new Date().toISOString();
      const tmpFile = `${DB_FILE}.tmp`;
      fs.writeFileSync(tmpFile, JSON.stringify(this.data, null, 2), 'utf8');
      fs.renameSync(tmpFile, DB_FILE);
      return true;
    } catch (e) {
      console.error('[Database Core] Atomic write error:', e.message);
      return false;
    }
  }

  // Get full database dump
  getAll() {
    return this.data;
  }

  // --- MEMORY ENGINE ---
  getMemories() {
    const vectorList = vectorMemory.getAllMemories();
    if (vectorList && vectorList.length > 0) {
      return vectorList;
    }
    return this.data.memories || [];
  }

  addMemory(text, category = 'general') {
    const newItem = vectorMemory.addMemory(text, category);
    this.data.memories = vectorMemory.getAllMemories();
    this.save();
    return { item: newItem, memories: this.data.memories };
  }

  deleteMemory(id) {
    const numId = parseInt(id, 10);
    vectorMemory.deleteMemory(numId);
    this.data.memories = vectorMemory.getAllMemories();
    this.save();
    return this.data.memories;
  }

  // --- ANALYTICS ---
  getAnalytics() {
    const data = this.data.analytics || DEFAULT_SCHEMA.analytics;
    const uptimeSeconds = Math.floor((Date.now() - (data.startTime || Date.now())) / 1000);
    return { ...data, uptimeSeconds };
  }

  incrementMetric(metric) {
    if (!this.data.analytics) this.data.analytics = { ...DEFAULT_SCHEMA.analytics };
    if (this.data.analytics[metric] !== undefined) {
      this.data.analytics[metric] += 1;
    } else {
      this.data.analytics[metric] = 1;
    }
    this.save();
    return this.getAnalytics();
  }

  // --- RESERVATIONS ---
  getReservations() {
    return this.data.reservations || [];
  }

  saveReservation(reservation) {
    if (!this.data.reservations) this.data.reservations = [];
    this.data.reservations.unshift(reservation);
    this.save();
    return this.data.reservations;
  }

  deleteReservation(id) {
    this.data.reservations = (this.data.reservations || []).filter(r => r.id !== id);
    this.save();
    return this.data.reservations;
  }

  // --- CHAT HISTORY ---
  getChatHistory() {
    return this.data.chat_history || [];
  }

  saveChatHistory(chats) {
    this.data.chat_history = Array.isArray(chats) ? chats : [];
    this.save();
    return this.data.chat_history;
  }

  addChatEntry(query, response) {
    if (!this.data.chat_history) this.data.chat_history = [];
    const newEntry = {
      id: Date.now(),
      query,
      response,
      timestamp: new Date().toLocaleString()
    };
    this.data.chat_history.unshift(newEntry);
    
    // Auto-extract long term memories from user queries
    vectorMemory.extractMemoriesFromText(query);
    this.data.memories = vectorMemory.getAllMemories();
    
    this.save();
    return newEntry;
  }

  deleteChatEntry(id) {
    const numId = parseInt(id, 10);
    this.data.chat_history = (this.data.chat_history || []).filter(c => c.id !== numId && c.id !== id);
    this.save();
    return this.data.chat_history;
  }

  // --- REMINDERS ---
  getReminders() {
    return this.data.reminders || [];
  }

  saveReminders(reminders) {
    this.data.reminders = Array.isArray(reminders) ? reminders : [];
    this.save();
    return this.data.reminders;
  }

  addReminder(reminder) {
    if (!this.data.reminders) this.data.reminders = [];
    const item = {
      id: reminder.id || Date.now(),
      title: reminder.title || 'Untitled Reminder',
      time: reminder.time || '12:00 PM',
      date: reminder.date || 'Today',
      category: reminder.category || 'General',
      completed: !!reminder.completed,
      createdAt: new Date().toISOString()
    };
    this.data.reminders.unshift(item);
    this.save();
    return this.data.reminders;
  }

  deleteReminder(id) {
    const numId = parseInt(id, 10);
    this.data.reminders = (this.data.reminders || []).filter(r => r.id !== numId && r.id !== id);
    this.save();
    return this.data.reminders;
  }

  // --- AUTOMATIONS ---
  getAutomations() {
    return this.data.automations || [];
  }

  saveAutomations(automations) {
    this.data.automations = Array.isArray(automations) ? automations : [];
    this.save();
    return this.data.automations;
  }

  // --- HEALTH VITALS ---
  getHealthVitals() {
    return this.data.health_vitals || [];
  }

  addHealthVital(vital) {
    if (!this.data.health_vitals) this.data.health_vitals = [];
    const entry = {
      id: Date.now(),
      bpm: vital.bpm || 74,
      spO2: vital.spO2 || 98,
      steps: vital.steps || 0,
      calories: vital.calories || 0,
      stress: vital.stress || 20,
      hrv: vital.hrv || 65,
      device: vital.device || 'Fitband',
      status: vital.status || 'Normal',
      timestamp: new Date().toLocaleTimeString()
    };
    this.data.health_vitals.unshift(entry);
    // Keep max 100 historical readings
    if (this.data.health_vitals.length > 100) {
      this.data.health_vitals = this.data.health_vitals.slice(0, 100);
    }
    this.save();
    return entry;
  }

  // --- SETTINGS ---
  getSettings() {
    return this.data.settings || {};
  }

  updateSettings(newSettings) {
    this.data.settings = { ...this.data.settings, ...newSettings };
    this.save();
    return this.data.settings;
  }

  // --- FACE BIOMETRIC PROFILE ---
  getFaceProfile() {
    return this.data.settings?.ownerFaceProfile || null;
  }

  saveFaceProfile(profile) {
    if (!this.data.settings) this.data.settings = {};
    this.data.settings.ownerFaceProfile = profile;
    this.save();
    return this.data.settings.ownerFaceProfile;
  }

  // --- SOCIAL CHANNELS & CREDENTIALS ---
  getSocialAccounts() {
    if (!this.data.social_accounts) {
      this.data.social_accounts = {
        instagram: { username: '@jwalant', password: '', sessionCookie: '', status: 'configured', lastAuthenticated: new Date().toISOString() },
        whatsapp: { senderNumber: '+91 98200 12345', countryCode: '+91', status: 'connected', lastLinked: new Date().toISOString() }
      };
      this.save();
    }
    return this.data.social_accounts;
  }

  saveSocialAccounts(accounts) {
    const current = this.getSocialAccounts();
    this.data.social_accounts = {
      instagram: { ...current.instagram, ...(accounts.instagram || {}) },
      whatsapp: { ...current.whatsapp, ...(accounts.whatsapp || {}) }
    };
    this.save();
    return this.data.social_accounts;
  }

  // --- SOCIAL CONTACTS & RECENT CONVERSATIONS ---
  getSocialContacts() {
    if (!this.data.social_contacts) {
      this.data.social_contacts = JSON.parse(JSON.stringify(DEFAULT_SCHEMA.social_contacts));
      this.save();
    }
    return this.data.social_contacts;
  }

  saveSocialContacts(contacts) {
    this.data.social_contacts = contacts;
    this.save();
    return this.data.social_contacts;
  }

  addSocialContact(contact) {
    const contacts = this.getSocialContacts();
    const newContact = {
      id: `c_${Date.now()}`,
      name: contact.name || 'New Contact',
      phone: contact.phone || '',
      ig: contact.ig ? (contact.ig.startsWith('@') ? contact.ig : `@${contact.ig}`) : '',
      platform: contact.platform || 'whatsapp',
      lastMessage: contact.lastMessage || '',
      lastTimestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      avatarColor: contact.avatarColor || 'from-cyan-500 to-blue-500'
    };
    contacts.unshift(newContact);
    this.saveSocialContacts(contacts);
    return newContact;
  }

  // --- SOCIAL AUTO-REPLY & AUTOMATED MESSAGING ---
  getSocialAutoReplyConfig() {
    if (!this.data.social_auto_reply) {
      this.data.social_auto_reply = JSON.parse(JSON.stringify(DEFAULT_SCHEMA.social_auto_reply));
      this.save();
    }
    return this.data.social_auto_reply;
  }

  saveSocialAutoReplyConfig(config) {
    this.data.social_auto_reply = { ...this.getSocialAutoReplyConfig(), ...config };
    this.save();
    return this.data.social_auto_reply;
  }

  getSocialLogs() {
    return this.data.social_logs || [];
  }

  addSocialLog(logEntry) {
    if (!this.data.social_logs) this.data.social_logs = [];
    const entry = {
      id: `LOG-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      platform: logEntry.platform || 'whatsapp',
      type: logEntry.type || 'direct_send',
      recipient: logEntry.recipient || 'Unknown',
      recipientName: logEntry.recipientName || logEntry.recipient || 'Unknown Contact',
      incomingTextOrCall: logEntry.incomingTextOrCall || 'Direct Automated Send',
      actionTaken: logEntry.actionTaken || 'Automated Message Dispatched',
      messageSent: logEntry.messageSent || '',
      status: logEntry.status || 'Delivered',
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      date: new Date().toISOString()
    };
    this.data.social_logs.unshift(entry);
    if (this.data.social_logs.length > 100) {
      this.data.social_logs = this.data.social_logs.slice(0, 100);
    }
    this.save();
    return entry;
  }

  clearSocialLogs() {
    this.data.social_logs = [];
    this.save();
    return [];
  }

  // --- FINANCE, ACCOUNTS & GUARDIAN BUDGET CORE ---
  getFinanceData() {
    if (!this.data.finance) {
      this.data.finance = JSON.parse(JSON.stringify(DEFAULT_SCHEMA.finance));
      this.save();
    }
    const fin = this.data.finance;
    if (!fin.accounts) fin.accounts = [];
    if (!fin.transactions) fin.transactions = [];
    if (!fin.budget) fin.budget = { ...DEFAULT_SCHEMA.finance.budget };
    if (!fin.settings) fin.settings = { defaultCurrency: '₹', privacyMask: false };

    // Calculate live analytics
    let liquidBalance = 0;
    let creditUsed = 0;
    let creditLimitTotal = 0;

    fin.accounts.forEach(acc => {
      const bal = Number(acc.balance) || 0;
      if (acc.type === 'credit') {
        creditUsed += bal;
        creditLimitTotal += (Number(acc.limit) || 0);
      } else {
        liquidBalance += bal;
      }
    });

    const netWorth = liquidBalance - creditUsed;

    // Monthly Spend & Income Calculation
    const now = new Date();
    const currentMonth = now.getMonth();
    const currentYear = now.getFullYear();

    let monthSpend = 0;
    let monthIncome = 0;
    const categoryTotals = {};

    fin.transactions.forEach(tx => {
      const txDate = new Date(tx.date || Date.now());
      const isThisMonth = txDate.getMonth() === currentMonth && txDate.getFullYear() === currentYear;
      const amount = Number(tx.amount) || 0;

      if (tx.type === 'expense') {
        if (isThisMonth) monthSpend += amount;
        const cat = tx.category || 'General';
        categoryTotals[cat] = (categoryTotals[cat] || 0) + amount;
      } else if (tx.type === 'income') {
        if (isThisMonth) monthIncome += amount;
      }
    });

    // Budget Status
    const budgetLimit = Number(fin.budget.monthlyLimit) || 2000;
    const thresholdPercent = Number(fin.budget.alertThresholdPercent) || 85;
    const percentSpent = budgetLimit > 0 ? Math.round((monthSpend / budgetLimit) * 100) : 0;
    let budgetState = 'safe'; // 'safe' | 'warning' | 'breached'
    if (percentSpent >= 100) {
      budgetState = 'breached';
    } else if (percentSpent >= thresholdPercent) {
      budgetState = 'warning';
    }

    // Daily Burn Rate (using 30-day window or current month days)
    const daysPassedInMonth = Math.max(1, now.getDate());
    const dailyBurnRate = monthSpend > 0 ? Math.round((monthSpend / daysPassedInMonth) * 100) / 100 : Math.round((budgetLimit / 30) * 100) / 100;
    const runwayDays = dailyBurnRate > 0 ? Math.max(0, Math.floor(liquidBalance / dailyBurnRate)) : 999;

    // Trajectory Forecasting (30, 60, 90 days)
    const dailyIncomeEst = monthIncome > 0 ? monthIncome / 30 : 0;
    const netDailyFlow = dailyIncomeEst - dailyBurnRate;
    const projected30 = Math.round(liquidBalance + (netDailyFlow * 30));
    const projected60 = Math.round(liquidBalance + (netDailyFlow * 60));
    const projected90 = Math.round(liquidBalance + (netDailyFlow * 90));

    // Category Breakdown Percentages
    const categoryBreakdown = Object.entries(categoryTotals).map(([name, total]) => ({
      name,
      amount: Math.round(total * 100) / 100,
      percentage: monthSpend > 0 ? Math.round((total / monthSpend) * 100) : 0
    })).sort((a, b) => b.amount - a.amount);

    // AI Savings Recommendations based on categories
    const recommendations = [];
    const topCategory = categoryBreakdown[0];
    if (topCategory && topCategory.percentage > 30) {
      recommendations.push({
        id: 'rec_1',
        title: `High Burn in ${topCategory.name}`,
        desc: `${topCategory.name} accounts for ${topCategory.percentage}% of your expenses ($${topCategory.amount}). Reducing this by 20% would preserve $${Math.round(topCategory.amount * 0.20)} every month.`,
        impact: `+$${Math.round(topCategory.amount * 0.20)}/mo`,
        type: 'high_burn'
      });
    }

    if (creditUsed > (creditLimitTotal * 0.4) && creditLimitTotal > 0) {
      recommendations.push({
        id: 'rec_2',
        title: 'Credit Utilization Warning',
        desc: `Credit card utilization is at ${Math.round((creditUsed / creditLimitTotal) * 100)}%. Pay down $${Math.round(creditUsed - creditLimitTotal * 0.3)} to keep utilization under the optimal 30% mark.`,
        impact: 'Boost Score',
        type: 'credit'
      });
    }

    recommendations.push({
      id: 'rec_3',
      title: 'Vault Runway Target',
      desc: `At current burn rate ($${dailyBurnRate}/day), your emergency reserves last ${runwayDays} days. Aim for a 90-day liquid reserve of $${Math.round(dailyBurnRate * 90)}.`,
      impact: `${runwayDays}d safety`,
      type: 'runway'
    });

    return {
      accounts: fin.accounts,
      budget: {
        ...fin.budget,
        monthSpend: Math.round(monthSpend * 100) / 100,
        monthIncome: Math.round(monthIncome * 100) / 100,
        percentSpent,
        remainingBudget: Math.max(0, Math.round((budgetLimit - monthSpend) * 100) / 100),
        state: budgetState
      },
      transactions: fin.transactions,
      settings: fin.settings,
      analytics: {
        liquidBalance: Math.round(liquidBalance * 100) / 100,
        creditUsed: Math.round(creditUsed * 100) / 100,
        creditLimitTotal: Math.round(creditLimitTotal * 100) / 100,
        netWorth: Math.round(netWorth * 100) / 100,
        dailyBurnRate,
        runwayDays,
        projections: {
          d30: projected30,
          d60: projected60,
          d90: projected90
        },
        categoryBreakdown,
        recommendations
      }
    };
  }

  addPaymentAccount(account) {
    if (!this.data.finance) this.getFinanceData();
    const newAccount = {
      id: `acc_${Date.now()}`,
      name: account.name || 'New Account',
      type: account.type || 'bank', // bank, savings, wallet, credit, cash
      balance: Number(account.balance) || 0,
      limit: account.type === 'credit' ? (Number(account.limit) || 2000) : 0,
      currency: account.currency || this.data.finance.settings?.defaultCurrency || '$',
      institution: account.institution || 'Personal Vault',
      isDefault: !!account.isDefault,
      color: account.color || 'from-cyan-600 to-blue-700',
      createdAt: new Date().toISOString()
    };

    if (newAccount.isDefault) {
      this.data.finance.accounts.forEach(a => { a.isDefault = false; });
    }
    this.data.finance.accounts.push(newAccount);
    this.save();
    return newAccount;
  }

  updatePaymentAccount(id, updates) {
    if (!this.data.finance) this.getFinanceData();
    const idx = this.data.finance.accounts.findIndex(a => a.id === id);
    if (idx === -1) return null;

    if (updates.isDefault) {
      this.data.finance.accounts.forEach(a => { a.isDefault = false; });
    }

    const current = this.data.finance.accounts[idx];
    this.data.finance.accounts[idx] = {
      ...current,
      ...updates,
      balance: updates.balance !== undefined ? Number(updates.balance) : current.balance,
      limit: updates.limit !== undefined ? Number(updates.limit) : current.limit
    };

    this.save();
    return this.data.finance.accounts[idx];
  }

  deletePaymentAccount(id) {
    if (!this.data.finance) this.getFinanceData();
    this.data.finance.accounts = this.data.finance.accounts.filter(a => a.id !== id);
    this.save();
    return this.data.finance.accounts;
  }

  addTransaction(tx) {
    if (!this.data.finance) this.getFinanceData();
    const amount = Math.abs(Number(tx.amount) || 0);
    const type = tx.type || 'expense'; // 'expense', 'income', 'transfer'

    const newTx = {
      id: `tx_${Date.now()}`,
      date: tx.date || new Date().toISOString(),
      accountId: tx.accountId || this.data.finance.accounts[0]?.id || 'acc_1',
      toAccountId: tx.toAccountId || null,
      type,
      amount,
      category: tx.category || (type === 'income' ? 'Income' : 'General Expense'),
      description: tx.description || 'Transaction',
      merchant: tx.merchant || '',
      tags: tx.tags || []
    };

    // Update account balances atomically
    const acc = this.data.finance.accounts.find(a => a.id === newTx.accountId);
    if (acc) {
      if (type === 'expense') {
        acc.balance = Math.round((Number(acc.balance) - amount) * 100) / 100;
      } else if (type === 'income') {
        acc.balance = Math.round((Number(acc.balance) + amount) * 100) / 100;
      } else if (type === 'transfer' && newTx.toAccountId) {
        acc.balance = Math.round((Number(acc.balance) - amount) * 100) / 100;
        const targetAcc = this.data.finance.accounts.find(a => a.id === newTx.toAccountId);
        if (targetAcc) {
          targetAcc.balance = Math.round((Number(targetAcc.balance) + amount) * 100) / 100;
        }
      }
    }

    this.data.finance.transactions.unshift(newTx);
    if (this.data.finance.transactions.length > 500) {
      this.data.finance.transactions = this.data.finance.transactions.slice(0, 500);
    }

    // Check Budget Limit & Guardian Protocol
    const summary = this.getFinanceData();
    let shouldAlertGuardian = false;
    let guardianAlertDetails = null;

    if (type === 'expense' && summary.budget.guardianAlertsEnabled && summary.budget.state === 'breached') {
      const lastAlert = summary.budget.lastAlertDispatchedAt ? new Date(summary.budget.lastAlertDispatchedAt).getTime() : 0;
      const cooldownMs = (Number(summary.budget.cooldownHours) || 24) * 3600 * 1000;
      const isPastCooldown = (Date.now() - lastAlert) > cooldownMs;

      if (isPastCooldown) {
        shouldAlertGuardian = true;
        guardianAlertDetails = {
          guardianName: summary.budget.guardianName || 'Guardian',
          guardianPhone: summary.budget.guardianPhone || '',
          guardianPlatform: summary.budget.guardianPlatform || 'whatsapp',
          limit: summary.budget.monthlyLimit,
          currentSpend: summary.budget.monthSpend,
          excessAmount: Math.round((summary.budget.monthSpend - summary.budget.monthlyLimit) * 100) / 100,
          latestExpense: `${newTx.description} (${summary.settings.defaultCurrency}${amount})`
        };
        this.data.finance.budget.lastAlertDispatchedAt = new Date().toISOString();
      }
    }

    this.save();
    return {
      transaction: newTx,
      financeSummary: summary,
      shouldAlertGuardian,
      guardianAlertDetails
    };
  }

  deleteTransaction(id) {
    if (!this.data.finance) this.getFinanceData();
    const tx = this.data.finance.transactions.find(t => t.id === id);
    if (tx) {
      // Reverse balance impact
      const acc = this.data.finance.accounts.find(a => a.id === tx.accountId);
      const amount = Number(tx.amount) || 0;
      if (acc) {
        if (tx.type === 'expense') {
          acc.balance = Math.round((Number(acc.balance) + amount) * 100) / 100;
        } else if (tx.type === 'income') {
          acc.balance = Math.round((Number(acc.balance) - amount) * 100) / 100;
        } else if (tx.type === 'transfer' && tx.toAccountId) {
          acc.balance = Math.round((Number(acc.balance) + amount) * 100) / 100;
          const targetAcc = this.data.finance.accounts.find(a => a.id === tx.toAccountId);
          if (targetAcc) {
            targetAcc.balance = Math.round((Number(targetAcc.balance) - amount) * 100) / 100;
          }
        }
      }
      this.data.finance.transactions = this.data.finance.transactions.filter(t => t.id !== id);
      this.save();
    }
    return this.getFinanceData();
  }

  transferFunds({ fromAccountId, toAccountId, amount, description = 'Internal Transfer' }) {
    return this.addTransaction({
      accountId: fromAccountId,
      toAccountId,
      type: 'transfer',
      amount,
      category: 'Transfer',
      description
    });
  }

  updateBudgetSettings(updates) {
    if (!this.data.finance) this.getFinanceData();
    this.data.finance.budget = {
      ...this.data.finance.budget,
      ...updates
    };
    this.save();
    return this.getFinanceData();
  }

  recordGuardianAlert(alertRecord) {
    if (!this.data.finance) this.getFinanceData();
    if (!this.data.finance.budget.alertsHistory) this.data.finance.budget.alertsHistory = [];
    const entry = {
      id: `ALT-${Date.now()}`,
      date: new Date().toISOString(),
      type: alertRecord.type || 'breach',
      message: alertRecord.message || 'Guardian Alert Dispatched',
      deliveredTo: alertRecord.deliveredTo || '',
      status: alertRecord.status || 'Delivered'
    };
    this.data.finance.budget.alertsHistory.unshift(entry);
    if (this.data.finance.budget.alertsHistory.length > 50) {
      this.data.finance.budget.alertsHistory = this.data.finance.budget.alertsHistory.slice(0, 50);
    }
    this.save();
    return entry;
  }

  updateFinanceSettings(updates) {
    if (!this.data.finance) this.getFinanceData();
    this.data.finance.settings = {
      ...this.data.finance.settings,
      ...updates
    };
    this.save();
    return this.data.finance.settings;
  }

  // --- IMPORT / EXPORT ---
  exportBackup() {
    return {
      backupDate: new Date().toISOString(),
      data: this.data
    };
  }

  importBackup(backupObj) {
    if (!backupObj || !backupObj.data) throw new Error('Invalid database backup file format');
    this.data = backupObj.data;
    this.save();
    return this.data;
  }
}

const dbManager = new DatabaseManager();
module.exports = dbManager;
