const fs = require('fs');
const path = require('path');
const vectorMemory = require('./vectorMemory');

// Target directory & file path for database
const DATA_DIR = path.join(__dirname, 'data');
const DB_FILE = path.join(DATA_DIR, 'jasper.db.json');

// Existing legacy files for automatic seamless migration
const LEGACY_MEMORY = path.join(__dirname, 'memory_store.json');
const LEGACY_ANALYTICS = path.join(__dirname, 'analytics_store.json');
const LEGACY_ACTIONS = path.join(__dirname, 'agentic_actions_store.json');
const LEGACY_TV = path.join(__dirname, 'tv-config.json');

// Ensure data directory exists
if (!fs.existsSync(DATA_DIR)) {
  fs.mkdirSync(DATA_DIR, { recursive: true });
}

// Initial Database Schema
const DEFAULT_SCHEMA = {
  version: 1.0,
  lastUpdated: new Date().toISOString(),
  memories: [
    { id: 1, text: 'User prefers concise audio responses', category: 'preference', date: new Date().toISOString() },
    { id: 2, text: 'Default smart home TV is Samsung Frame in Living Room', category: 'device', date: new Date().toISOString() }
  ],
  analytics: {
    conversations: 42,
    voiceCommands: 128,
    imagesGenerated: 15,
    automationRuns: 24,
    connectedDevices: 3,
    startTime: Date.now()
  },
  reservations: [
    {
      id: 'RES-DEMO-01',
      venueName: 'Trattoria Bella Vista',
      cuisine: 'Italian Fine Dining',
      partySize: 4,
      date: 'Tomorrow',
      time: '8:30 PM',
      confirmationCode: 'JSP-8821',
      contactName: 'Jwalant',
      phone: '+1 (555) 382-9901',
      address: '450 Grand Avenue, Suite 12',
      specialRequests: 'Quiet garden booth',
      createdAt: new Date().toISOString(),
      status: 'Confirmed'
    }
  ],
  chat_history: [
    {
      id: 1,
      query: 'who is narendra modi',
      response: 'Narendra Damodardas Modi is an Indian politician who has served as the prime minister of India since 2014.',
      timestamp: new Date().toLocaleString()
    }
  ],
  reminders: [
    {
      id: 1,
      title: 'Review System Diagnostics',
      time: '09:00 AM',
      date: 'Today',
      category: 'System',
      completed: false,
      createdAt: new Date().toISOString()
    }
  ],
  automations: [
    {
      id: 'auto-1',
      name: 'Morning Wakeup Routine',
      trigger: 'Voice Command: "Good Morning"',
      action: 'Set Volume 50%, Fetch Weather, Play Music',
      enabled: true,
      createdAt: new Date().toISOString()
    }
  ],
  health_vitals: [
    {
      id: Date.now(),
      bpm: 74,
      spO2: 98,
      steps: 6480,
      calories: 320,
      stress: 22,
      hrv: 65,
      device: 'Virtual Fitband Pro',
      status: 'Normal',
      timestamp: new Date().toLocaleTimeString()
    }
  ],
  social_accounts: {
    instagram: {
      username: '@jwalant',
      password: '',
      sessionCookie: '',
      status: 'configured',
      lastAuthenticated: new Date().toISOString()
    },
    whatsapp: {
      senderNumber: '+91 98200 12345',
      countryCode: '+91',
      status: 'connected',
      lastLinked: new Date().toISOString()
    }
  },
  social_auto_reply: {
    whatsappEnabled: true,
    instagramEnabled: true,
    callAutoDeclineAndMsg: true,
    activePreset: 'drive',
    presets: {
      drive: "🚗 Drive Mode: I'm currently driving. JASPER AI has recorded your message and I will reply as soon as I park.",
      meeting: "💼 Deep Work / Meeting Mode: I am currently in a meeting. Will review your message shortly.",
      sleep: "🌙 DND Mode: Sleeping right now. Auto-reply generated by JASPER Assistant. Type URGENT for emergencies.",
      ai_smart: "🤖 Context-aware AI Smart Responder active via Gemini neural engine.",
      custom: "I am currently away from my phone. I'll get back to you soon!"
    },
    aiSmartPrompt: "Formulate a polite, professional, and friendly 1-2 sentence automated reply on behalf of Jwalant.",
    emergencyKeyword: "URGENT",
    whitelistContacts: ["Mom", "Sarah (Office Boss)"]
  },
  social_contacts: [
    { id: 'c1', name: 'Mom', phone: '+91 98200 12345', ig: '@mom_family', platform: 'whatsapp', lastMessage: '🚗 Drive Mode: I\'m currently driving...', lastTimestamp: '10:42 PM', avatarColor: 'from-pink-500 to-rose-500' },
    { id: 'c2', name: 'Fatih Makes', phone: '+1 555 382 9901', ig: '@fatihmakes', platform: 'instagram', lastMessage: 'Automated test DM sent from Jwalant\'s connected Instagram account!', lastTimestamp: '11:45 PM', avatarColor: 'from-purple-500 to-indigo-500' },
    { id: 'c3', name: 'Sarah (Office Boss)', phone: '+91 98233 45678', ig: '@sarah_lead', platform: 'whatsapp', lastMessage: '💼 Deep Work Mode: I am currently in a meeting.', lastTimestamp: '08:15 PM', avatarColor: 'from-blue-500 to-cyan-500' },
    { id: 'c4', name: 'Alex (Auto Mechanic)', phone: '+91 98222 34567', ig: '@alex_mechanic', platform: 'instagram', lastMessage: 'Car inspection report ready for pickup!', lastTimestamp: 'Yesterday', avatarColor: 'from-amber-500 to-orange-500' },
    { id: 'c5', name: 'Dr. Mehta (Dentist)', phone: '+91 98211 23456', ig: '@mehta_clinic', platform: 'whatsapp', lastMessage: 'Appointment scheduled for Tuesday at 4:00 PM', lastTimestamp: 'Aug 28', avatarColor: 'from-emerald-500 to-teal-500' }
  ],
  social_logs: [
    {
      id: "LOG-01",
      platform: "whatsapp",
      type: "call_auto_reply",
      recipient: "+91 98200 12345",
      recipientName: "Mom",
      incomingTextOrCall: "Incoming WhatsApp Call",
      actionTaken: "Declined Call & Sent WhatsApp Auto-Reply",
      messageSent: "🚗 Drive Mode: I'm currently driving. JASPER AI has recorded your message and I will reply as soon as I park.",
      status: "Delivered",
      timestamp: "10:42 PM"
    },
    {
      id: "LOG-02",
      platform: "instagram",
      type: "msg_auto_reply",
      recipient: "@fatihmakes",
      recipientName: "Fatih Makes",
      incomingTextOrCall: "Hey! Can you send the CAD files?",
      actionTaken: "AI Smart Agent Auto-Replied to Instagram DM",
      messageSent: "Hey Fatih! Jwalant is in deep focus mode right now. He will send over the files as soon as he is back at the workstation!",
      status: "Delivered",
      timestamp: "10:35 PM"
    }
  ],
  settings: {
    theme: 'cyber-blue',
    serverIp: 'localhost',
    fitbandMac: 'F4:67:F4:16:7C:53',
    pcMac: '74:12:B3:ED:1C:BF'
  }
};

class DatabaseManager {
  constructor() {
    this.data = this.init();
  }

  // Load database or initialize with migrations
  init() {
    let dbData = null;

    if (fs.existsSync(DB_FILE)) {
      try {
        const content = fs.readFileSync(DB_FILE, 'utf8');
        dbData = JSON.parse(content);
        console.log('[Database Core] Loaded database from:', DB_FILE);
      } catch (e) {
        console.error('[Database Core] Database file read error, recreating schema:', e.message);
      }
    }

    if (!dbData) {
      dbData = JSON.parse(JSON.stringify(DEFAULT_SCHEMA));
      this.migrateLegacyFiles(dbData);
      this.save(dbData);
    } else {
      // Ensure all tables exist in loaded dbData
      for (const key of Object.keys(DEFAULT_SCHEMA)) {
        if (dbData[key] === undefined) {
          dbData[key] = DEFAULT_SCHEMA[key];
        }
      }
    }

    return dbData;
  }

  // Migrate legacy individual JSON files if they exist
  migrateLegacyFiles(dbData) {
    console.log('[Database Core] Checking legacy JSON files for data migration...');
    try {
      if (fs.existsSync(LEGACY_MEMORY)) {
        const mem = JSON.parse(fs.readFileSync(LEGACY_MEMORY, 'utf8'));
        if (mem.memories && Array.isArray(mem.memories)) {
          dbData.memories = mem.memories;
          console.log(`[Database Core] Migrated ${mem.memories.length} legacy memory records.`);
        }
      }
    } catch (e) {}

    try {
      if (fs.existsSync(LEGACY_ANALYTICS)) {
        const ana = JSON.parse(fs.readFileSync(LEGACY_ANALYTICS, 'utf8'));
        dbData.analytics = { ...dbData.analytics, ...ana };
        console.log('[Database Core] Migrated legacy analytics counters.');
      }
    } catch (e) {}

    try {
      if (fs.existsSync(LEGACY_ACTIONS)) {
        const act = JSON.parse(fs.readFileSync(LEGACY_ACTIONS, 'utf8'));
        if (Array.isArray(act)) {
          dbData.reservations = act;
          console.log(`[Database Core] Migrated ${act.length} legacy reservations.`);
        }
      }
    } catch (e) {}

    try {
      if (fs.existsSync(LEGACY_TV)) {
        const tv = JSON.parse(fs.readFileSync(LEGACY_TV, 'utf8'));
        dbData.settings = { ...dbData.settings, tvConfig: tv };
        console.log('[Database Core] Migrated legacy TV config.');
      }
    } catch (e) {}
  }

  // Save database with atomic file write (.tmp -> rename)
  save(dataToSave = this.data) {
    try {
      dataToSave.lastUpdated = new Date().toISOString();
      const tmpFile = `${DB_FILE}.tmp`;
      fs.writeFileSync(tmpFile, JSON.stringify(dataToSave, null, 2), 'utf8');
      fs.renameSync(tmpFile, DB_FILE);
      this.data = dataToSave;
      return true;
    } catch (e) {
      console.error('[Database Core] Atomic write error:', e.message);
      return false;
    }
  }

  // Get full database dump
  getAll() {
    return this.data;
  }

  // --- MEMORY ENGINE ---
  getMemories() {
    const vectorList = vectorMemory.getAllMemories();
    if (vectorList && vectorList.length > 0) {
      return vectorList;
    }
    return this.data.memories || [];
  }

  addMemory(text, category = 'general') {
    const newItem = vectorMemory.addMemory(text, category);
    this.data.memories = vectorMemory.getAllMemories();
    this.save();
    return { item: newItem, memories: this.data.memories };
  }

  deleteMemory(id) {
    const numId = parseInt(id, 10);
    vectorMemory.deleteMemory(numId);
    this.data.memories = vectorMemory.getAllMemories();
    this.save();
    return this.data.memories;
  }

  // --- ANALYTICS ---
  getAnalytics() {
    const data = this.data.analytics || DEFAULT_SCHEMA.analytics;
    const uptimeSeconds = Math.floor((Date.now() - (data.startTime || Date.now())) / 1000);
    return { ...data, uptimeSeconds };
  }

  incrementMetric(metric) {
    if (!this.data.analytics) this.data.analytics = { ...DEFAULT_SCHEMA.analytics };
    if (this.data.analytics[metric] !== undefined) {
      this.data.analytics[metric] += 1;
    } else {
      this.data.analytics[metric] = 1;
    }
    this.save();
    return this.getAnalytics();
  }

  // --- RESERVATIONS ---
  getReservations() {
    return this.data.reservations || [];
  }

  saveReservation(reservation) {
    if (!this.data.reservations) this.data.reservations = [];
    this.data.reservations.unshift(reservation);
    this.save();
    return this.data.reservations;
  }

  deleteReservation(id) {
    this.data.reservations = (this.data.reservations || []).filter(r => r.id !== id);
    this.save();
    return this.data.reservations;
  }

  // --- CHAT HISTORY ---
  getChatHistory() {
    return this.data.chat_history || [];
  }

  saveChatHistory(chats) {
    this.data.chat_history = Array.isArray(chats) ? chats : [];
    this.save();
    return this.data.chat_history;
  }

  addChatEntry(query, response) {
    if (!this.data.chat_history) this.data.chat_history = [];
    const newEntry = {
      id: Date.now(),
      query,
      response,
      timestamp: new Date().toLocaleString()
    };
    this.data.chat_history.unshift(newEntry);
    
    // Auto-extract long term memories from user queries
    vectorMemory.extractMemoriesFromText(query);
    this.data.memories = vectorMemory.getAllMemories();
    
    this.save();
    return newEntry;
  }

  deleteChatEntry(id) {
    const numId = parseInt(id, 10);
    this.data.chat_history = (this.data.chat_history || []).filter(c => c.id !== numId && c.id !== id);
    this.save();
    return this.data.chat_history;
  }

  // --- REMINDERS ---
  getReminders() {
    return this.data.reminders || [];
  }

  saveReminders(reminders) {
    this.data.reminders = Array.isArray(reminders) ? reminders : [];
    this.save();
    return this.data.reminders;
  }

  addReminder(reminder) {
    if (!this.data.reminders) this.data.reminders = [];
    const item = {
      id: reminder.id || Date.now(),
      title: reminder.title || 'Untitled Reminder',
      time: reminder.time || '12:00 PM',
      date: reminder.date || 'Today',
      category: reminder.category || 'General',
      completed: !!reminder.completed,
      createdAt: new Date().toISOString()
    };
    this.data.reminders.unshift(item);
    this.save();
    return this.data.reminders;
  }

  deleteReminder(id) {
    const numId = parseInt(id, 10);
    this.data.reminders = (this.data.reminders || []).filter(r => r.id !== numId && r.id !== id);
    this.save();
    return this.data.reminders;
  }

  // --- AUTOMATIONS ---
  getAutomations() {
    return this.data.automations || [];
  }

  saveAutomations(automations) {
    this.data.automations = Array.isArray(automations) ? automations : [];
    this.save();
    return this.data.automations;
  }

  // --- HEALTH VITALS ---
  getHealthVitals() {
    return this.data.health_vitals || [];
  }

  addHealthVital(vital) {
    if (!this.data.health_vitals) this.data.health_vitals = [];
    const entry = {
      id: Date.now(),
      bpm: vital.bpm || 74,
      spO2: vital.spO2 || 98,
      steps: vital.steps || 0,
      calories: vital.calories || 0,
      stress: vital.stress || 20,
      hrv: vital.hrv || 65,
      device: vital.device || 'Fitband',
      status: vital.status || 'Normal',
      timestamp: new Date().toLocaleTimeString()
    };
    this.data.health_vitals.unshift(entry);
    // Keep max 100 historical readings
    if (this.data.health_vitals.length > 100) {
      this.data.health_vitals = this.data.health_vitals.slice(0, 100);
    }
    this.save();
    return entry;
  }

  // --- SETTINGS ---
  getSettings() {
    return this.data.settings || {};
  }

  updateSettings(newSettings) {
    this.data.settings = { ...this.data.settings, ...newSettings };
    this.save();
    return this.data.settings;
  }

  // --- FACE BIOMETRIC PROFILE ---
  getFaceProfile() {
    return this.data.settings?.ownerFaceProfile || null;
  }

  saveFaceProfile(profile) {
    if (!this.data.settings) this.data.settings = {};
    this.data.settings.ownerFaceProfile = profile;
    this.save();
    return this.data.settings.ownerFaceProfile;
  }

  // --- SOCIAL CHANNELS & CREDENTIALS ---
  getSocialAccounts() {
    if (!this.data.social_accounts) {
      this.data.social_accounts = {
        instagram: { username: '@jwalant', password: '', sessionCookie: '', status: 'configured', lastAuthenticated: new Date().toISOString() },
        whatsapp: { senderNumber: '+91 98200 12345', countryCode: '+91', status: 'connected', lastLinked: new Date().toISOString() }
      };
      this.save();
    }
    return this.data.social_accounts;
  }

  saveSocialAccounts(accounts) {
    const current = this.getSocialAccounts();
    this.data.social_accounts = {
      instagram: { ...current.instagram, ...(accounts.instagram || {}) },
      whatsapp: { ...current.whatsapp, ...(accounts.whatsapp || {}) }
    };
    this.save();
    return this.data.social_accounts;
  }

  // --- SOCIAL CONTACTS & RECENT CONVERSATIONS ---
  getSocialContacts() {
    if (!this.data.social_contacts) {
      this.data.social_contacts = JSON.parse(JSON.stringify(DEFAULT_SCHEMA.social_contacts));
      this.save();
    }
    return this.data.social_contacts;
  }

  saveSocialContacts(contacts) {
    this.data.social_contacts = contacts;
    this.save();
    return this.data.social_contacts;
  }

  addSocialContact(contact) {
    const contacts = this.getSocialContacts();
    const newContact = {
      id: `c_${Date.now()}`,
      name: contact.name || 'New Contact',
      phone: contact.phone || '',
      ig: contact.ig ? (contact.ig.startsWith('@') ? contact.ig : `@${contact.ig}`) : '',
      platform: contact.platform || 'whatsapp',
      lastMessage: contact.lastMessage || '',
      lastTimestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      avatarColor: contact.avatarColor || 'from-cyan-500 to-blue-500'
    };
    contacts.unshift(newContact);
    this.saveSocialContacts(contacts);
    return newContact;
  }

  // --- SOCIAL AUTO-REPLY & AUTOMATED MESSAGING ---
  getSocialAutoReplyConfig() {
    if (!this.data.social_auto_reply) {
      this.data.social_auto_reply = JSON.parse(JSON.stringify(DEFAULT_SCHEMA.social_auto_reply));
      this.save();
    }
    return this.data.social_auto_reply;
  }

  saveSocialAutoReplyConfig(config) {
    this.data.social_auto_reply = { ...this.getSocialAutoReplyConfig(), ...config };
    this.save();
    return this.data.social_auto_reply;
  }

  getSocialLogs() {
    return this.data.social_logs || [];
  }

  addSocialLog(logEntry) {
    if (!this.data.social_logs) this.data.social_logs = [];
    const entry = {
      id: `LOG-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      platform: logEntry.platform || 'whatsapp',
      type: logEntry.type || 'direct_send',
      recipient: logEntry.recipient || 'Unknown',
      recipientName: logEntry.recipientName || logEntry.recipient || 'Unknown Contact',
      incomingTextOrCall: logEntry.incomingTextOrCall || 'Direct Automated Send',
      actionTaken: logEntry.actionTaken || 'Automated Message Dispatched',
      messageSent: logEntry.messageSent || '',
      status: logEntry.status || 'Delivered',
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      date: new Date().toISOString()
    };
    this.data.social_logs.unshift(entry);
    if (this.data.social_logs.length > 100) {
      this.data.social_logs = this.data.social_logs.slice(0, 100);
    }
    this.save();
    return entry;
  }

  clearSocialLogs() {
    this.data.social_logs = [];
    this.save();
    return [];
  }

  // --- IMPORT / EXPORT ---
  exportBackup() {
    return {
      backupDate: new Date().toISOString(),
      data: this.data
    };
  }

  importBackup(backupObj) {
    if (!backupObj || !backupObj.data) throw new Error('Invalid database backup file format');
    this.data = backupObj.data;
    this.save();
    return this.data;
  }
}

const dbManager = new DatabaseManager();
module.exports = dbManager;
