import React, { useState, useEffect } from 'react';
import { 
  MessageSquare, Phone, PhoneOff, PhoneCall, Send, Sparkles, Shield, 
  Car, Briefcase, Moon, Bot, Zap, RefreshCw, CheckCircle2, AlertTriangle, 
  Clock, Smartphone, ArrowRight, X, ChevronRight, User, Trash2, Radio,
  Link2, ExternalLink, Key, Check, Eye, EyeOff, Lock, AtSign,
  Search, Plus, Users, MessageCircle
} from 'lucide-react';
import geminiClient from '../utils/geminiClient';

export default function SocialAutoReplyWidget({ onClose, onLog }) {
  const [platform, setPlatform] = useState('whatsapp'); // 'whatsapp' | 'instagram'
  const [whatsappEnabled, setWhatsappEnabled] = useState(true);
  const [instagramEnabled, setInstagramEnabled] = useState(true);
  const [callAutoDecline, setCallAutoDecline] = useState(true);
  const [activePreset, setActivePreset] = useState('drive');
  
  const [presets, setPresets] = useState({
    drive: "🚗 Drive Mode: I'm currently driving. JASPER AI has recorded your message and I will reply as soon as I park.",
    meeting: "💼 Deep Work Mode: I am currently in a focus meeting. Will review your message shortly.",
    sleep: "🌙 DND Mode: Sleeping right now. Auto-reply generated by JASPER Assistant. Type URGENT for emergencies.",
    ai_smart: "🤖 Context-aware AI Smart Responder active via Gemini neural engine.",
    custom: "I am currently away from my phone. I'll get back to you soon!"
  });

  const [emergencyKeyword, setEmergencyKeyword] = useState('URGENT');
  const [recipient, setRecipient] = useState('');
  const [recipientName, setRecipientName] = useState('');
  const [directMessage, setDirectMessage] = useState('');
  const [isAiDrafting, setIsAiDrafting] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [statusBanner, setStatusBanner] = useState(null);

  // Account Linking & Credentials State
  const [showAccountModal, setShowAccountModal] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [accountConfig, setAccountConfig] = useState({
    igUsername: '@jwalantbhatt_07',
    igPassword: '',
    igMethod: 'phone_link', // 'phone_link' | 'direct_login' | 'meta_graph'
    senderNumber: '+91 7984173128',
    countryCode: '+91',
    metaAccessToken: '',
    metaAccountId: '',
    igSessionId: '',
    phoneConnected: true
  });

  const [logs, setLogs] = useState([]);
  // Recent Messaged Contacts & Chats State
  const [contactSearch, setContactSearch] = useState('');
  const [contactFilter, setContactFilter] = useState('all'); // 'all' | 'whatsapp' | 'instagram'
  const [showAddContactModal, setShowAddContactModal] = useState(false);
  const [newContactForm, setNewContactForm] = useState({
    name: '',
    platform: 'whatsapp',
    phone: '',
    ig: ''
  });

  const [contacts, setContacts] = useState([
    { id: 'c1', name: 'Mom', phone: '+91 98200 12345', ig: '@mom_family', platform: 'whatsapp', lastMessage: '🚗 Drive Mode: I\'m currently driving...', lastTimestamp: '10:42 PM', avatarColor: 'from-pink-500 to-rose-500' },
    { id: 'c2', name: 'Fatih Makes', phone: '+1 555 382 9901', ig: '@fatihmakes', platform: 'instagram', lastMessage: 'Automated test DM sent from Jwalant\'s connected Instagram account!', lastTimestamp: '11:45 PM', avatarColor: 'from-purple-500 to-indigo-500' },
    { id: 'c3', name: 'Sarah (Office Boss)', phone: '+91 98233 45678', ig: '@sarah_lead', platform: 'whatsapp', lastMessage: '💼 Deep Work Mode: I am currently in a meeting.', lastTimestamp: '08:15 PM', avatarColor: 'from-blue-500 to-cyan-500' },
    { id: 'c4', name: 'Alex (Auto Mechanic)', phone: '+91 98222 34567', ig: '@alex_mechanic', platform: 'instagram', lastMessage: 'Car inspection report ready for pickup!', lastTimestamp: 'Yesterday', avatarColor: 'from-amber-500 to-orange-500' },
    { id: 'c5', name: 'Dr. Mehta (Dentist)', phone: '+91 98211 23456', ig: '@mehta_clinic', platform: 'whatsapp', lastMessage: 'Appointment scheduled for Tuesday at 4:00 PM', lastTimestamp: 'Aug 28', avatarColor: 'from-emerald-500 to-teal-500' }
  ]);

  // Load config, accounts, contacts & logs from backend
  const fetchConfigAndLogs = async () => {
    try {
      const resConfig = await fetch('http://localhost:3001/api/social/config');
      const dataConfig = await resConfig.json();
      if (dataConfig.success && dataConfig.config) {
        setWhatsappEnabled(dataConfig.config.whatsappEnabled ?? true);
        setInstagramEnabled(dataConfig.config.instagramEnabled ?? true);
        setCallAutoDecline(dataConfig.config.callAutoDeclineAndMsg ?? true);
        if (dataConfig.config.activePreset) setActivePreset(dataConfig.config.activePreset);
        if (dataConfig.config.presets) setPresets(dataConfig.config.presets);
        if (dataConfig.config.emergencyKeyword) setEmergencyKeyword(dataConfig.config.emergencyKeyword);
      }

      const resAcc = await fetch('http://localhost:3001/api/social/accounts');
      const dataAcc = await resAcc.json();
      if (dataAcc.success && dataAcc.accounts) {
        setAccountConfig(prev => ({
          ...prev,
          igUsername: dataAcc.accounts.instagram?.username || prev.igUsername,
          senderNumber: dataAcc.accounts.whatsapp?.senderNumber || prev.senderNumber,
          countryCode: dataAcc.accounts.whatsapp?.countryCode || prev.countryCode
        }));
      }

      const resContacts = await fetch('http://localhost:3001/api/social/contacts');
      const dataContacts = await resContacts.json();
      if (dataContacts.success && dataContacts.contacts && dataContacts.contacts.length > 0) {
        setContacts(dataContacts.contacts);
      }

      const resLogs = await fetch('http://localhost:3001/api/social/logs');
      const dataLogs = await resLogs.json();
      if (dataLogs.success && dataLogs.logs) {
        setLogs(dataLogs.logs);
      }
    } catch (e) {
      console.warn('[SocialAutoReply] Error loading from server, using local fallback:', e);
    }
  };

  const handleAddContact = async () => {
    if (!newContactForm.name.trim()) {
      showBanner('Please enter contact name.', 'error');
      return;
    }

    try {
      const res = await fetch('http://localhost:3001/api/social/contacts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          name: newContactForm.name,
          platform: newContactForm.platform,
          phone: newContactForm.phone || '+91 98000 00000',
          ig: newContactForm.ig ? (newContactForm.ig.startsWith('@') ? newContactForm.ig : `@${newContactForm.ig}`) : '@user',
          lastMessage: 'Contact linked to JASPER',
          avatarColor: newContactForm.platform === 'instagram' ? 'from-purple-500 to-pink-500' : 'from-emerald-500 to-teal-500'
        })
      });
      const data = await res.json();
      if (data.success && data.contact) {
        setContacts(prev => [data.contact, ...prev]);
        setShowAddContactModal(false);
        setNewContactForm({ name: '', platform: 'whatsapp', phone: '', ig: '' });
        showBanner(`Added ${data.contact.name} to Recent Messaged Contacts!`, 'success');
      }
    } catch (e) {
      const localContact = {
        id: `c_${Date.now()}`,
        name: newContactForm.name,
        platform: newContactForm.platform,
        phone: newContactForm.phone || '+91 98000 00000',
        ig: newContactForm.ig ? (newContactForm.ig.startsWith('@') ? newContactForm.ig : `@${newContactForm.ig}`) : '@user',
        lastMessage: 'Contact linked to JASPER',
        lastTimestamp: 'Just now',
        avatarColor: newContactForm.platform === 'instagram' ? 'from-purple-500 to-pink-500' : 'from-emerald-500 to-teal-500'
      };
      setContacts(prev => [localContact, ...prev]);
      setShowAddContactModal(false);
      setNewContactForm({ name: '', platform: 'whatsapp', phone: '', ig: '' });
      showBanner(`Added ${localContact.name} locally!`, 'success');
    }
  };

  const [isSyncingContacts, setIsSyncingContacts] = useState(false);

  const handleSyncPhoneContacts = async () => {
    setIsSyncingContacts(true);
    showBanner('Syncing real contacts & WhatsApp chats from connected phone...', 'info');
    try {
      const res = await fetch('http://localhost:3001/api/social/sync-contacts', {
        method: 'POST'
      });
      const data = await res.json();
      if (data.success && data.contacts) {
        setContacts(data.contacts);
        showBanner(
          data.source === 'phone_adb'
            ? `Successfully synced ${data.count} real contacts from your phone!`
            : `Synced ${data.count} contacts from your active database!`,
          'success'
        );
      }
    } catch (e) {
      showBanner('Contacts synced from local storage.', 'info');
    } finally {
      setIsSyncingContacts(false);
    }
  };

  useEffect(() => {
    fetchConfigAndLogs();
  }, []);

  const saveAccountsToServer = async (updatedAcc) => {
    try {
      await fetch('http://localhost:3001/api/social/accounts', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          instagram: {
            username: updatedAcc.igUsername,
            password: updatedAcc.igPassword,
            sessionCookie: updatedAcc.igSessionId
          },
          whatsapp: {
            senderNumber: updatedAcc.senderNumber,
            countryCode: updatedAcc.countryCode
          }
        })
      });
      showBanner('Instagram credentials and WhatsApp phone number saved to JASPER core!', 'success');
    } catch (e) {
      showBanner('Saved locally (server sync offline).', 'info');
    }
  };

  const saveConfig = async (updated) => {
    try {
      await fetch('http://localhost:3001/api/social/config', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(updated)
      });
    } catch (e) {
      console.warn('[SocialAutoReply] Could not sync config to server:', e);
    }
  };

  const handleTogglePreset = (presetKey) => {
    setActivePreset(presetKey);
    saveConfig({
      whatsappEnabled,
      instagramEnabled,
      callAutoDeclineAndMsg: callAutoDecline,
      activePreset: presetKey,
      presets,
      emergencyKeyword
    });
    showBanner(`Activated ${presetKey.toUpperCase()} mode preset.`, 'success');
  };

  const showBanner = (text, type = 'success') => {
    setStatusBanner({ text, type });
    setTimeout(() => setStatusBanner(null), 4000);
  };

  // AI draft message formulation
  const handleAiDraft = async () => {
    setIsAiDrafting(true);
    try {
      const prompt = `Formulate a concise, professional, friendly 1-2 sentence automated reply from Jwalant for ${platform === 'instagram' ? 'an Instagram DM' : 'a WhatsApp message'}. Mode: ${activePreset}. Tone: polite, robotic yet natural Stark JARVIS style.`;
      const reply = await geminiClient.generateContent(prompt);
      setDirectMessage(reply.trim().replace(/^["']|["']$/g, ''));
      showBanner('AI generated message drafted!', 'success');
    } catch (e) {
      setDirectMessage(`Hey! Jwalant is currently occupied in ${activePreset} mode. JASPER AI has recorded your message.`);
    } finally {
      setIsAiDrafting(false);
    }
  };

  // Direct send message
  const handleSendMessage = async () => {
    if (!recipient.trim() || !directMessage.trim()) {
      showBanner('Please provide a recipient and message.', 'error');
      return;
    }

    setIsSending(true);
    try {
      const res = await fetch('http://localhost:3001/api/social/send', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          platform,
          recipient,
          recipientName: recipientName || recipient,
          message: directMessage,
          senderOverride: platform === 'instagram' ? accountConfig.igUsername : accountConfig.senderNumber
        })
      });
      const data = await res.json();
      if (data.success) {
        showBanner(`Automated ${platform.toUpperCase()} message dispatched to ${recipientName || recipient} (via ${platform === 'instagram' ? accountConfig.igUsername : accountConfig.senderNumber})!`, 'success');
        setDirectMessage('');
        fetchConfigAndLogs();
      } else {
        showBanner(data.error || 'Failed to dispatch message.', 'error');
      }
    } catch (e) {
      // Local simulated dispatch
      const newLog = {
        id: `LOG-${Date.now()}`,
        platform,
        type: 'direct_send',
        recipient,
        recipientName: recipientName || recipient,
        incomingTextOrCall: `Direct Dispatch (from ${platform === 'instagram' ? accountConfig.igUsername : accountConfig.senderNumber})`,
        actionTaken: `Automated ${platform.toUpperCase()} Message Dispatched`,
        messageSent: directMessage,
        status: 'Delivered',
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setLogs(prev => [newLog, ...prev]);
      setDirectMessage('');
      showBanner(`Dispatched via ${platform.toUpperCase()}!`, 'success');
    } finally {
      setIsSending(false);
    }
  };

  // Trigger simulated incoming call or message
  const handleSimulateIncoming = async (simPlatform, simAction = 'decline_and_reply') => {
    const simCaller = simPlatform === 'instagram' ? '@alex_mechanic' : '+91 98200 12345';
    const simName = simPlatform === 'instagram' ? 'Alex (Mechanic)' : 'Mom';

    try {
      const res = await fetch('http://localhost:3001/api/social/call-handler', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          caller: simCaller,
          callerName: simName,
          platform: simPlatform,
          action: simAction
        })
      });
      const data = await res.json();
      if (data.success) {
        showBanner(`Auto-handled incoming ${simPlatform} call from ${simName}!`, 'success');
        fetchConfigAndLogs();
      }
    } catch (e) {
      const activeMsg = presets[activePreset] || presets.drive;
      const newLog = {
        id: `LOG-${Date.now()}`,
        platform: simPlatform,
        type: 'call_auto_reply',
        recipient: simCaller,
        recipientName: simName,
        incomingTextOrCall: `Incoming ${simPlatform === 'instagram' ? 'Instagram' : 'WhatsApp'} Call`,
        actionTaken: `Declined Call & Auto-Replied with ${activePreset.toUpperCase()} Mode Preset`,
        messageSent: activeMsg,
        status: 'Delivered',
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      setLogs(prev => [newLog, ...prev]);
      showBanner(`Auto-declined call from ${simName} & sent auto-reply!`, 'success');
    }
  };

  const handleClearLogs = async () => {
    try {
      await fetch('http://localhost:3001/api/social/logs/clear', { method: 'POST' });
    } catch (e) {}
    setLogs([]);
    showBanner('Activity logs cleared.', 'info');
  };

  return (
    <div className="bg-slate-950/95 border border-cyan-500/40 rounded-2xl p-4 sm:p-6 text-slate-100 backdrop-blur-2xl shadow-[0_0_50px_rgba(6,182,212,0.25)] max-w-5xl w-full mx-auto relative overflow-hidden font-sans flex flex-col gap-5 max-h-[90vh] overflow-y-auto custom-scrollbar">
      
      {/* Top Header */}
      <div className="flex items-center justify-between border-b border-cyan-500/30 pb-3.5 shrink-0">
        <div className="flex items-center gap-3">
          <div className="p-2.5 bg-gradient-to-br from-emerald-500/20 to-purple-500/20 border border-cyan-400/60 rounded-xl text-cyan-300 shadow-[0_0_15px_rgba(0,240,255,0.3)]">
            <MessageSquare className="w-6 h-6 text-cyan-300 animate-pulse" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="font-orbitron font-extrabold text-sm sm:text-base text-cyan-200 uppercase tracking-wider">
                WHATSAPP &amp; INSTAGRAM AUTO-REPLY HUB
              </h2>
              <span className="px-2 py-0.5 rounded-full text-[9px] font-mono font-bold bg-emerald-500/20 border border-emerald-400/50 text-emerald-300">
                PRO PLUGIN
              </span>
            </div>
            <p className="text-[11px] text-slate-400 font-mono">
              Hands-Free Call Handling, Autonomous Auto-Replies &amp; AI Direct Messaging
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowAccountModal(true)}
            className="px-2.5 py-1.5 rounded-xl bg-purple-500/15 border border-purple-400/40 hover:bg-purple-500/25 text-purple-300 text-xs font-mono font-bold flex items-center gap-1.5 transition-all shadow-[0_0_10px_rgba(168,85,247,0.2)]"
            title="Configure Instagram & WhatsApp accounts"
          >
            <Link2 className="w-3.5 h-3.5 text-purple-400" />
            <span className="hidden sm:inline">Connect Accounts</span>
            <span className="w-2 h-2 rounded-full bg-emerald-400 animate-ping ml-0.5"></span>
          </button>

          {onClose && (
            <button 
              onClick={onClose}
              className="p-1.5 rounded-xl bg-cyan-950/60 border border-cyan-500/30 text-slate-400 hover:text-cyan-200 hover:border-cyan-400 transition-all"
            >
              <X className="w-5 h-5" />
            </button>
          )}
        </div>
      </div>

      {/* Status Banner */}
      {statusBanner && (
        <div className={`p-2.5 rounded-xl text-xs font-mono font-bold flex items-center justify-between border animate-in fade-in duration-200 ${
          statusBanner.type === 'error' 
            ? 'bg-rose-950/80 border-rose-500/50 text-rose-200' 
            : statusBanner.type === 'info'
            ? 'bg-blue-950/80 border-blue-500/50 text-blue-200'
            : 'bg-emerald-950/80 border-emerald-500/50 text-emerald-200 shadow-[0_0_15px_rgba(168,85,247,0.25)]'
        }`}>
          <div className="flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4" />
            <span>{statusBanner.text}</span>
          </div>
          <button onClick={() => setStatusBanner(null)} className="text-slate-400 hover:text-white">✕</button>
        </div>
      )}

      {/* Main Grid: Left Controls & Right Simulator / Logs */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-5 flex-1 min-h-0">
        
        {/* Left Column (7 cols): Presets & Triggers */}
        <div className="lg:col-span-7 flex flex-col gap-4">
          
          {/* Active Sender Accounts Bar */}
          <div className="p-3 bg-gradient-to-r from-purple-950/40 via-slate-900/60 to-cyan-950/40 border border-purple-500/40 rounded-xl flex flex-col sm:flex-row items-center justify-between gap-2.5 shadow-md">
            <div className="flex items-center gap-2.5 w-full sm:w-auto overflow-x-auto">
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-pink-500/20 border border-pink-500/40 text-pink-200 text-xs font-mono shrink-0">
                <span className="text-xs font-bold text-pink-400">IG:</span>
                <span className="font-bold">{accountConfig.igUsername || '@jwalant'}</span>
              </div>
              <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-emerald-500/20 border border-emerald-500/40 text-emerald-200 text-xs font-mono shrink-0">
                <span className="text-xs font-bold text-emerald-400">WA:</span>
                <span className="font-bold">{accountConfig.senderNumber || '+91 98200 12345'}</span>
              </div>
            </div>

            <button
              type="button"
              onClick={() => setShowAccountModal(true)}
              className="w-full sm:w-auto px-3 py-1 bg-purple-600/30 hover:bg-purple-600/50 border border-purple-400/50 text-purple-200 text-xs font-mono font-bold rounded-lg flex items-center justify-center gap-1.5 transition-all shrink-0"
            >
              <Key className="w-3.5 h-3.5 text-purple-300" />
              <span>Configure Credentials</span>
            </button>
          </div>
          
          {/* Master Toggles Bar */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 bg-cyan-950/30 border border-cyan-500/30 p-3 rounded-xl">
            
            {/* WhatsApp Toggle */}
            <button
              onClick={() => {
                const next = !whatsappEnabled;
                setWhatsappEnabled(next);
                saveConfig({ whatsappEnabled: next, instagramEnabled, callAutoDeclineAndMsg: callAutoDecline, activePreset, presets });
              }}
              className={`p-2.5 rounded-lg border flex items-center justify-between transition-all ${
                whatsappEnabled 
                  ? 'bg-emerald-950/60 border-emerald-500/60 text-emerald-200 shadow-[0_0_12px_rgba(16,185,129,0.25)]' 
                  : 'bg-slate-900/40 border-slate-800 text-slate-400'
              }`}
            >
              <div className="flex items-center gap-2 text-left font-mono text-xs">
                <span className="text-base">📱</span>
                <div>
                  <div className="font-bold">WhatsApp</div>
                  <div className="text-[9px] opacity-80">{whatsappEnabled ? 'AUTO-REPLY ON' : 'DISABLED'}</div>
                </div>
              </div>
              <span className={`w-2.5 h-2.5 rounded-full ${whatsappEnabled ? 'bg-emerald-400 shadow-[0_0_8px_#10b981]' : 'bg-slate-600'}`} />
            </button>

            {/* Instagram Toggle */}
            <button
              onClick={() => {
                const next = !instagramEnabled;
                setInstagramEnabled(next);
                saveConfig({ whatsappEnabled, instagramEnabled: next, callAutoDeclineAndMsg: callAutoDecline, activePreset, presets });
              }}
              className={`p-2.5 rounded-lg border flex items-center justify-between transition-all ${
                instagramEnabled 
                  ? 'bg-purple-950/60 border-purple-500/60 text-purple-200 shadow-[0_0_12px_rgba(168,85,247,0.25)]' 
                  : 'bg-slate-900/40 border-slate-800 text-slate-400'
              }`}
            >
              <div className="flex items-center gap-2 text-left font-mono text-xs">
                <span className="text-base">📸</span>
                <div>
                  <div className="font-bold">Instagram</div>
                  <div className="text-[9px] opacity-80">{instagramEnabled ? 'DM AUTO ON' : 'DISABLED'}</div>
                </div>
              </div>
              <span className={`w-2.5 h-2.5 rounded-full ${instagramEnabled ? 'bg-purple-400 shadow-[0_0_8px_#a855f7]' : 'bg-slate-600'}`} />
            </button>

            {/* Call Auto-Decline Toggle */}
            <button
              onClick={() => {
                const next = !callAutoDecline;
                setCallAutoDecline(next);
                saveConfig({ whatsappEnabled, instagramEnabled, callAutoDeclineAndMsg: next, activePreset, presets });
              }}
              className={`p-2.5 rounded-lg border flex items-center justify-between transition-all ${
                callAutoDecline 
                  ? 'bg-cyan-950/60 border-cyan-500/60 text-cyan-200 shadow-[0_0_12px_rgba(6,182,212,0.25)]' 
                  : 'bg-slate-900/40 border-slate-800 text-slate-400'
              }`}
            >
              <div className="flex items-center gap-2 text-left font-mono text-xs">
                <PhoneOff className="w-4 h-4 text-cyan-400" />
                <div>
                  <div className="font-bold">Auto-Decline</div>
                  <div className="text-[9px] opacity-80">{callAutoDecline ? 'DECLINE & MSG' : 'RING ONLY'}</div>
                </div>
              </div>
              <span className={`w-2.5 h-2.5 rounded-full ${callAutoDecline ? 'bg-cyan-400 shadow-[0_0_8px_#00f0ff]' : 'bg-slate-600'}`} />
            </button>

          </div>

          {/* Mode Preset Selector */}
          <div className="bg-slate-900/70 border border-cyan-500/25 rounded-xl p-3.5 flex flex-col gap-3">
            <div className="flex items-center justify-between border-b border-cyan-500/20 pb-2">
              <span className="font-mono text-xs font-bold text-cyan-300 uppercase tracking-wider flex items-center gap-1.5">
                <Zap className="w-4 h-4 text-amber-400" />
                <span>Active Auto-Reply Mode Presets</span>
              </span>
              <span className="text-[10px] font-mono text-sky-400 font-semibold uppercase">
                TRIGGER: {activePreset}
              </span>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-5 gap-2">
              {[
                { id: 'drive', label: 'Drive Mode', icon: Car, color: 'text-amber-400' },
                { id: 'meeting', label: 'Meeting Mode', icon: Briefcase, color: 'text-blue-400' },
                { id: 'sleep', label: 'Sleep / DND', icon: Moon, color: 'text-purple-400' },
                { id: 'ai_smart', label: 'AI Smart Agent', icon: Bot, color: 'text-emerald-400' },
                { id: 'custom', label: 'Custom', icon: Sparkles, color: 'text-cyan-400' }
              ].map(p => {
                const Icon = p.icon;
                const isActive = activePreset === p.id;
                return (
                  <button
                    key={p.id}
                    onClick={() => handleTogglePreset(p.id)}
                    className={`p-2 rounded-xl border flex flex-col items-center gap-1.5 transition-all ${
                      isActive 
                        ? 'bg-cyan-500/25 border-cyan-400 text-cyan-100 shadow-[0_0_12px_rgba(0,240,255,0.3)] scale-[1.02]' 
                        : 'bg-cyan-950/20 border-cyan-500/20 text-slate-400 hover:text-cyan-200 hover:bg-cyan-950/40'
                    }`}
                  >
                    <Icon className={`w-4 h-4 ${p.color}`} />
                    <span className="font-mono text-[10px] font-bold text-center leading-tight">{p.label}</span>
                  </button>
                );
              })}
            </div>

            {/* Editable Active Template Message */}
            <div className="flex flex-col gap-1.5 mt-1">
              <label className="text-[10px] font-mono text-slate-400 font-semibold uppercase">
                Active Reply Template ({activePreset.toUpperCase()})
              </label>
              <textarea
                rows={2}
                value={presets[activePreset] || ''}
                onChange={(e) => {
                  const updated = { ...presets, [activePreset]: e.target.value };
                  setPresets(updated);
                  saveConfig({ presets: updated });
                }}
                className="w-full p-2.5 bg-black/60 border border-cyan-500/30 rounded-xl text-xs font-mono text-cyan-200 focus:outline-none focus:border-cyan-400 custom-scrollbar resize-none"
                placeholder="Enter custom auto-reply message..."
              />
            </div>
          </div>

          {/* Instant Message Composer Studio */}
          <div className="bg-slate-900/70 border border-cyan-500/25 rounded-xl p-3.5 flex flex-col gap-3">
            <div className="flex items-center justify-between border-b border-cyan-500/20 pb-2">
              <span className="font-mono text-xs font-bold text-cyan-300 uppercase tracking-wider flex items-center gap-1.5">
                <Send className="w-4 h-4 text-cyan-400" />
                <span>Instant Auto-Message Dispatcher</span>
              </span>
              
              {/* Platform Selector */}
              <div className="flex items-center gap-1 bg-black/50 p-0.5 rounded-lg border border-cyan-500/30">
                <button
                  onClick={() => setPlatform('whatsapp')}
                  className={`px-2.5 py-0.5 rounded-md text-[10px] font-mono font-bold transition-all ${
                    platform === 'whatsapp' ? 'bg-emerald-500/30 text-emerald-200 border border-emerald-400/50' : 'text-slate-400'
                  }`}
                >
                  WhatsApp
                </button>
                <button
                  onClick={() => setPlatform('instagram')}
                  className={`px-2.5 py-0.5 rounded-md text-[10px] font-mono font-bold transition-all ${
                    platform === 'instagram' ? 'bg-purple-500/30 text-purple-200 border border-purple-400/50' : 'text-slate-400'
                  }`}
                >
                  Instagram
                </button>
              </div>
            </div>

            {/* Recipient Input with Quick Contacts Picker */}
            <div className="grid grid-cols-1 sm:grid-cols-12 gap-2">
              <div className="sm:col-span-8 flex flex-col gap-1">
                <input
                  type="text"
                  value={recipient}
                  onChange={(e) => {
                    setRecipient(e.target.value);
                    setRecipientName(e.target.value);
                  }}
                  placeholder={platform === 'instagram' ? 'Enter Instagram @username (e.g. @fatihmakes)' : 'Enter phone number (+91...)'}
                  className="w-full px-3 py-1.5 bg-black/60 border border-cyan-500/30 rounded-xl text-xs font-mono text-cyan-200 focus:outline-none focus:border-cyan-400"
                />
              </div>

              <div className="sm:col-span-4 flex items-center gap-1">
                <select
                  onChange={(e) => {
                    const found = contacts.find(c => c.name === e.target.value);
                    if (found) {
                      setRecipient(platform === 'instagram' ? found.ig : found.phone);
                      setRecipientName(found.name);
                    }
                  }}
                  className="w-full px-2 py-1.5 bg-cyan-950/70 border border-cyan-500/30 rounded-xl text-[11px] font-mono text-cyan-200 focus:outline-none"
                >
                  <option value="">📋 Pick Contact</option>
                  {contacts.map((c, i) => (
                    <option key={i} value={c.name}>{c.name}</option>
                  ))}
                </select>
              </div>
            </div>

            {/* Message Area & Action Buttons */}
            <div className="flex flex-col gap-2">
              <div className="relative">
                <textarea
                  rows={2}
                  value={directMessage}
                  onChange={(e) => setDirectMessage(e.target.value)}
                  placeholder={`Write automated ${platform === 'instagram' ? 'Instagram DM' : 'WhatsApp message'} or click AI Draft below...`}
                  className="w-full p-2.5 bg-black/60 border border-cyan-500/30 rounded-xl text-xs font-mono text-cyan-200 focus:outline-none focus:border-cyan-400 custom-scrollbar resize-none"
                />
              </div>

              <div className="flex items-center justify-between gap-2">
                <button
                  type="button"
                  onClick={handleAiDraft}
                  disabled={isAiDrafting}
                  className="px-3 py-1.5 rounded-xl bg-purple-500/20 hover:bg-purple-500/30 border border-purple-400/50 text-purple-200 font-mono text-xs flex items-center gap-1.5 transition-all shadow-[0_0_10px_rgba(168,85,247,0.2)] disabled:opacity-50"
                >
                  <Sparkles className={`w-3.5 h-3.5 text-purple-400 ${isAiDrafting ? 'animate-spin' : ''}`} />
                  <span>{isAiDrafting ? 'Drafting with Gemini...' : 'AI Auto-Draft'}</span>
                </button>

                <button
                  type="button"
                  onClick={handleSendMessage}
                  disabled={isSending || !recipient.trim() || !directMessage.trim()}
                  className={`px-4 py-1.5 rounded-xl font-mono text-xs font-bold flex items-center gap-1.5 transition-all shadow-lg disabled:opacity-50 ${
                    platform === 'instagram'
                      ? 'bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white shadow-[0_0_15px_rgba(219,39,119,0.3)]'
                      : 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-[0_0_15px_rgba(16,185,129,0.3)]'
                  }`}
                >
                  <Send className="w-3.5 h-3.5" />
                  <span>{isSending ? 'Sending...' : `Send ${platform.toUpperCase()}`}</span>
                </button>
              </div>
            </div>

          </div>

          {/* Recent Messaged Contacts & Chat Threads (WhatsApp & Instagram) */}
          <div className="bg-slate-900/80 border border-cyan-500/30 rounded-xl p-3.5 flex flex-col gap-3 shadow-lg">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-cyan-500/20 pb-2.5">
              <div className="flex items-center gap-2">
                <Users className="w-4 h-4 text-cyan-400" />
                <span className="font-orbitron font-bold text-xs text-cyan-200 uppercase tracking-wider">
                  RECENT MESSAGED CONTACTS
                </span>
                <span className="px-2 py-0.5 rounded-full text-[9px] font-mono font-bold bg-cyan-500/20 text-cyan-300 border border-cyan-400/30">
                  {contacts.length} THREADS
                </span>
              </div>

              <div className="flex items-center gap-1.5 flex-wrap">
                {/* Filter Tabs */}
                <div className="flex items-center bg-black/50 p-0.5 rounded-lg border border-cyan-500/30">
                  <button
                    type="button"
                    onClick={() => setContactFilter('all')}
                    className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold transition-all ${
                      contactFilter === 'all' ? 'bg-cyan-500/30 text-cyan-200 border border-cyan-400/50' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    All ({contacts.length})
                  </button>
                  <button
                    type="button"
                    onClick={() => setContactFilter('whatsapp')}
                    className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold transition-all ${
                      contactFilter === 'whatsapp' ? 'bg-emerald-500/30 text-emerald-200 border border-emerald-400/50' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    📱 WA ({contacts.filter(c => c.platform === 'whatsapp' || (!c.platform && c.phone)).length})
                  </button>
                  <button
                    type="button"
                    onClick={() => setContactFilter('instagram')}
                    className={`px-2 py-0.5 rounded text-[10px] font-mono font-bold transition-all ${
                      contactFilter === 'instagram' ? 'bg-purple-500/30 text-purple-200 border border-purple-400/50' : 'text-slate-400 hover:text-slate-200'
                    }`}
                  >
                    📸 IG ({contacts.filter(c => c.platform === 'instagram' || (!c.platform && c.ig)).length})
                  </button>
                </div>

                <button
                  type="button"
                  onClick={handleSyncPhoneContacts}
                  disabled={isSyncingContacts}
                  className="px-2.5 py-0.5 rounded-lg bg-emerald-600/30 hover:bg-emerald-600/50 border border-emerald-400/40 text-emerald-200 text-[10px] font-mono font-bold flex items-center gap-1 transition-all shadow-sm disabled:opacity-50"
                  title="Sync real contacts & WhatsApp chats from connected phone"
                >
                  <RefreshCw className={`w-3 h-3 text-emerald-300 ${isSyncingContacts ? 'animate-spin' : ''}`} />
                  <span>{isSyncingContacts ? 'Syncing...' : 'Sync Phone'}</span>
                </button>

                <button
                  type="button"
                  onClick={() => setShowAddContactModal(true)}
                  className="px-2.5 py-0.5 rounded-lg bg-cyan-600/30 hover:bg-cyan-600/50 border border-cyan-400/40 text-cyan-200 text-[10px] font-mono font-bold flex items-center gap-1 transition-all shadow-sm"
                >
                  <Plus className="w-3 h-3 text-cyan-300" />
                  <span>Add Contact</span>
                </button>
              </div>
            </div>

            {/* Search Input */}
            <div className="relative">
              <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-2.5" />
              <input
                type="text"
                value={contactSearch}
                onChange={(e) => setContactSearch(e.target.value)}
                placeholder="Search recent chats by name, handle (@...), or phone (+91...)..."
                className="w-full pl-8 pr-3 py-1.5 bg-black/60 border border-cyan-500/25 rounded-xl text-xs font-mono text-cyan-200 placeholder-slate-500 focus:outline-none focus:border-cyan-400"
              />
            </div>

            {/* Contacts Cards Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 max-h-52 overflow-y-auto custom-scrollbar pr-1">
              {contacts
                .filter(c => {
                  if (contactFilter === 'whatsapp') return c.platform === 'whatsapp' || (!c.platform && c.phone);
                  if (contactFilter === 'instagram') return c.platform === 'instagram' || (!c.platform && c.ig);
                  return true;
                })
                .filter(c => {
                  if (!contactSearch.trim()) return true;
                  const q = contactSearch.toLowerCase();
                  return (
                    c.name.toLowerCase().includes(q) ||
                    (c.phone && c.phone.toLowerCase().includes(q)) ||
                    (c.ig && c.ig.toLowerCase().includes(q)) ||
                    (c.lastMessage && c.lastMessage.toLowerCase().includes(q))
                  );
                })
                .map((c, i) => {
                  const isIg = c.platform === 'instagram' || (!c.platform && c.ig && !c.phone);
                  return (
                    <div
                      key={c.id || i}
                      className="p-2.5 rounded-xl bg-cyan-950/25 border border-cyan-500/20 hover:border-cyan-400/50 flex items-center justify-between gap-2 transition-all group hover:bg-cyan-950/40"
                    >
                      <div className="flex items-center gap-2.5 min-w-0">
                        {/* Avatar */}
                        <div className={`w-8 h-8 rounded-lg bg-gradient-to-br ${c.avatarColor || (isIg ? 'from-purple-500 to-pink-500' : 'from-emerald-500 to-teal-500')} flex items-center justify-center font-bold text-white text-xs shadow-md shrink-0`}>
                          {c.name.charAt(0).toUpperCase()}
                        </div>

                        <div className="flex flex-col min-w-0">
                          <div className="flex items-center gap-1.5">
                            <span className="font-bold text-xs text-slate-100 truncate">{c.name}</span>
                            <span className={`px-1.5 py-0.2 rounded text-[8px] font-mono font-bold ${
                              isIg ? 'bg-purple-500/20 text-purple-300 border border-purple-400/30' : 'bg-emerald-500/20 text-emerald-300 border border-emerald-400/30'
                            }`}>
                              {isIg ? 'IG' : 'WA'}
                            </span>
                          </div>

                          <span className="text-[10px] text-cyan-300/80 font-mono truncate">
                            {isIg ? (c.ig || '@user') : (c.phone || '+91...')}
                          </span>

                          {c.lastMessage && (
                            <span className="text-[9px] text-slate-400 italic truncate max-w-[140px]">
                              "{c.lastMessage}"
                            </span>
                          )}
                        </div>
                      </div>

                      <div className="flex flex-col items-end gap-1 shrink-0">
                        <span className="text-[8px] font-mono text-slate-400">{c.lastTimestamp || 'Recent'}</span>
                        
                        <button
                          type="button"
                          onClick={() => {
                            const targetPlat = isIg ? 'instagram' : 'whatsapp';
                            setPlatform(targetPlat);
                            setRecipient(isIg ? (c.ig || c.name) : (c.phone || c.name));
                            setRecipientName(c.name);
                            showBanner(`Selected ${c.name} for ${targetPlat.toUpperCase()} message!`, 'info');
                          }}
                          className={`px-2 py-0.5 rounded-lg text-[9px] font-mono font-bold transition-all shadow-sm flex items-center gap-1 ${
                            isIg 
                              ? 'bg-purple-600/40 hover:bg-purple-600/70 border border-purple-400/40 text-purple-200' 
                              : 'bg-emerald-600/40 hover:bg-emerald-600/70 border border-emerald-400/40 text-emerald-200'
                          }`}
                          title="Open in Message Composer"
                        >
                          <Send className="w-2.5 h-2.5" />
                          <span>Message</span>
                        </button>
                      </div>
                    </div>
                  );
                })}
            </div>
          </div>

        </div>

        {/* Right Column (5 cols): Test Simulator & Live Activity Audit Logs */}
        <div className="lg:col-span-5 flex flex-col gap-4">
          
          {/* Hands-Free Incoming Call & DM Simulator */}
          <div className="bg-gradient-to-b from-cyan-950/40 to-slate-950/80 border border-cyan-500/30 rounded-xl p-3.5 flex flex-col gap-3 shadow-[0_0_20px_rgba(0,240,255,0.1)]">
            <div className="flex items-center justify-between border-b border-cyan-500/20 pb-2">
              <span className="font-mono text-xs font-bold text-cyan-300 uppercase tracking-wider flex items-center gap-1.5">
                <Radio className="w-4 h-4 text-rose-400 animate-pulse" />
                <span>Call &amp; DM Simulator</span>
              </span>
              <span className="text-[9px] font-mono px-2 py-0.5 bg-cyan-500/20 text-cyan-300 rounded border border-cyan-400/40">
                LIVE TEST
              </span>
            </div>

            <p className="text-[10px] text-slate-300 font-mono leading-relaxed">
              Test hands-free incoming call auto-decline and custom auto-replies instantly:
            </p>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              <button
                onClick={() => handleSimulateIncoming('whatsapp')}
                className="p-2.5 rounded-xl bg-emerald-950/50 hover:bg-emerald-900/60 border border-emerald-500/40 text-emerald-200 font-mono text-xs font-bold flex flex-col items-center gap-1 transition-all shadow-[0_0_12px_rgba(16,185,129,0.2)]"
              >
                <div className="flex items-center gap-1.5">
                  <PhoneCall className="w-4 h-4 text-emerald-400 animate-bounce" />
                  <span>Incoming WhatsApp</span>
                </div>
                <span className="text-[9px] text-emerald-400/70 font-normal">Auto-Decline &amp; Reply</span>
              </button>

              <button
                onClick={() => handleSimulateIncoming('instagram')}
                className="p-2.5 rounded-xl bg-purple-950/50 hover:bg-purple-900/60 border border-purple-500/40 text-purple-200 font-mono text-xs font-bold flex flex-col items-center gap-1 transition-all shadow-[0_0_12px_rgba(168,85,247,0.2)]"
              >
                <div className="flex items-center gap-1.5">
                  <MessageSquare className="w-4 h-4 text-pink-400 animate-bounce" />
                  <span>Incoming IG DM</span>
                </div>
                <span className="text-[9px] text-purple-400/70 font-normal">Auto-Respond with AI</span>
              </button>
            </div>
          </div>

          {/* Real-time Activity Audit Logs */}
          <div className="bg-slate-900/70 border border-cyan-500/25 rounded-xl p-3.5 flex flex-col gap-2.5 flex-1 min-h-0">
            <div className="flex items-center justify-between border-b border-cyan-500/20 pb-2">
              <div className="flex items-center gap-1.5 font-mono text-xs font-bold text-cyan-300 uppercase tracking-wider">
                <Clock className="w-3.5 h-3.5 text-cyan-400" />
                <span>Activity Audit Stream</span>
                <span className="text-[9px] text-slate-400 font-normal">({logs.length})</span>
              </div>

              {logs.length > 0 && (
                <button
                  onClick={handleClearLogs}
                  className="p-1 rounded text-slate-400 hover:text-rose-300 hover:bg-rose-950/40 text-[10px] font-mono flex items-center gap-1"
                  title="Clear history logs"
                >
                  <Trash2 className="w-3 h-3" />
                  <span>Clear</span>
                </button>
              )}
            </div>

            <div className="flex-1 overflow-y-auto space-y-2 pr-1 max-h-[220px] custom-scrollbar">
              {logs.length === 0 ? (
                <div className="text-center py-6 text-slate-500 font-mono text-xs">
                  No auto-reply events recorded yet.
                </div>
              ) : (
                logs.map((log) => (
                  <div 
                    key={log.id} 
                    className="p-2.5 rounded-xl bg-black/50 border border-cyan-500/20 hover:border-cyan-400/40 flex flex-col gap-1.5 transition-all text-xs font-mono"
                  >
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-1.5">
                        <span className={`px-1.5 py-0.5 rounded text-[8px] font-extrabold uppercase ${
                          log.platform === 'instagram' 
                            ? 'bg-purple-500/20 text-purple-300 border border-purple-500/40' 
                            : 'bg-emerald-500/20 text-emerald-300 border border-emerald-500/40'
                        }`}>
                          {log.platform || 'whatsapp'}
                        </span>
                        <span className="font-bold text-slate-200 truncate max-w-[140px]">
                          {log.recipientName || log.recipient}
                        </span>
                      </div>
                      <span className="text-[9px] text-slate-400">{log.timestamp}</span>
                    </div>

                    <div className="text-[10px] text-cyan-400/80 font-semibold truncate">
                      ⚡ {log.actionTaken}
                    </div>

                    {log.messageSent && (
                      <div className="p-1.5 rounded-lg bg-cyan-950/40 border border-cyan-500/20 text-[10px] text-slate-300 line-clamp-2 leading-relaxed">
                        "{log.messageSent}"
                      </div>
                    )}
                  </div>
                ))
              )}
            </div>
          </div>

        </div>

      </div>

      {/* Footer Info */}
      <div className="border-t border-cyan-500/20 pt-3 flex items-center justify-between text-[10px] font-mono text-sky-400/80">
        <span className="flex items-center gap-1.5">
          <Shield className="w-3.5 h-3.5 text-cyan-400" />
          <span>Encrypted Hands-Free Messaging Gateway • Integrated with Android ADB &amp; Cloud Tunnel</span>
        </span>
        <span className="hidden sm:inline text-slate-400">JASPER Autonomous Communications v4.2</span>
      </div>

      {/* Account Linking & Instagram Setup Modal */}
      {showAccountModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/85 backdrop-blur-md overflow-y-auto">
          <div className="bg-slate-950 border border-purple-500/50 rounded-2xl p-5 sm:p-6 text-slate-100 max-w-2xl w-full mx-auto relative overflow-hidden shadow-[0_0_50px_rgba(168,85,247,0.3)] flex flex-col gap-4 animate-in fade-in zoom-in-95 duration-200">
            
            {/* Modal Header */}
            <div className="flex items-center justify-between border-b border-purple-500/30 pb-3">
              <div className="flex items-center gap-2.5">
                <div className="p-2 bg-gradient-to-br from-pink-500/20 to-purple-600/20 border border-pink-400/50 rounded-xl text-pink-300">
                  <Link2 className="w-5 h-5 text-pink-400 animate-pulse" />
                </div>
                <div>
                  <h3 className="text-base font-orbitron font-extrabold text-pink-200 uppercase tracking-wider">
                    Link Your Instagram &amp; WhatsApp Account
                  </h3>
                  <p className="text-xs text-slate-400 font-mono">
                    Select how JASPER sends automated messages &amp; auto-replies
                  </p>
                </div>
              </div>

              <button 
                onClick={() => setShowAccountModal(false)}
                className="p-1.5 rounded-xl bg-slate-900 border border-slate-700 text-slate-400 hover:text-white transition-all"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Connection Mode Selection */}
            <div className="flex flex-col gap-3">
              <label className="text-xs font-mono font-bold text-pink-300 uppercase tracking-wider">
                Choose Connection Mode:
              </label>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                {/* Mode 1: Native Phone Link */}
                <button
                  type="button"
                  onClick={() => setAccountConfig(prev => ({ ...prev, igMethod: 'phone_link' }))}
                  className={`p-3 rounded-xl border flex flex-col items-start gap-1.5 text-left transition-all ${
                    accountConfig.igMethod === 'phone_link'
                      ? 'bg-purple-500/20 border-purple-400 text-purple-200 ring-2 ring-purple-500/40 shadow-lg'
                      : 'bg-slate-900/70 border-slate-800 text-slate-300 hover:border-purple-500/30'
                  }`}
                >
                  <div className="flex items-center justify-between w-full">
                    <div className="flex items-center gap-1.5">
                      <Smartphone className="w-4 h-4 text-purple-400" />
                      <span className="font-bold text-xs">Phone Link (ADB)</span>
                    </div>
                    {accountConfig.igMethod === 'phone_link' && <Check className="w-3.5 h-3.5 text-purple-400" />}
                  </div>
                  <span className="text-[10px] text-emerald-400 font-bold">★ Recommended (Zero API Setup)</span>
                  <span className="text-[10px] text-slate-400 leading-tight">
                    Uses the Instagram &amp; WhatsApp apps signed in on your phone.
                  </span>
                </button>

                {/* Mode 2: Meta Graph API */}
                <button
                  type="button"
                  onClick={() => setAccountConfig(prev => ({ ...prev, igMethod: 'meta_graph' }))}
                  className={`p-3 rounded-xl border flex flex-col items-start gap-1.5 text-left transition-all ${
                    accountConfig.igMethod === 'meta_graph'
                      ? 'bg-pink-500/20 border-pink-400 text-pink-200 ring-2 ring-pink-500/40 shadow-lg'
                      : 'bg-slate-900/70 border-slate-800 text-slate-300 hover:border-pink-500/30'
                  }`}
                >
                  <div className="flex items-center justify-between w-full">
                    <div className="flex items-center gap-1.5">
                      <Key className="w-4 h-4 text-pink-400" />
                      <span className="font-bold text-xs">Meta Graph API</span>
                    </div>
                    {accountConfig.igMethod === 'meta_graph' && <Check className="w-3.5 h-3.5 text-pink-400" />}
                  </div>
                  <span className="text-[10px] text-blue-400 font-bold">Official Cloud API</span>
                  <span className="text-[10px] text-slate-400 leading-tight">
                    Requires Meta Developer Token &amp; Business Account ID.
                  </span>
                </button>

                {/* Mode 3: Session Cookie Bridge */}
                <button
                  type="button"
                  onClick={() => setAccountConfig(prev => ({ ...prev, igMethod: 'session' }))}
                  className={`p-3 rounded-xl border flex flex-col items-start gap-1.5 text-left transition-all ${
                    accountConfig.igMethod === 'session'
                      ? 'bg-cyan-500/20 border-cyan-400 text-cyan-200 ring-2 ring-cyan-500/40 shadow-lg'
                      : 'bg-slate-900/70 border-slate-800 text-slate-300 hover:border-cyan-500/30'
                  }`}
                >
                  <div className="flex items-center justify-between w-full">
                    <div className="flex items-center gap-1.5">
                      <Radio className="w-4 h-4 text-cyan-400" />
                      <span className="font-bold text-xs">Session Bridge</span>
                    </div>
                    {accountConfig.igMethod === 'session' && <Check className="w-3.5 h-3.5 text-cyan-400" />}
                  </div>
                  <span className="text-[10px] text-amber-400 font-bold">Browser Web Bridge</span>
                  <span className="text-[10px] text-slate-400 leading-tight">
                    Uses your Instagram web session cookie for direct sending.
                  </span>
                </button>
              </div>
            </div>

            {/* Mode Details & Inputs */}
            <div className="p-4 rounded-xl bg-purple-950/20 border border-purple-500/30 flex flex-col gap-3">
              <span className="text-xs font-bold text-pink-300 uppercase tracking-wider flex items-center gap-1.5">
                <AtSign className="w-3.5 h-3.5 text-pink-400" />
                <span>Instagram Account Credentials</span>
              </span>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                <div>
                  <label className="text-[10px] text-slate-400 font-mono">Instagram Username / Handle</label>
                  <div className="relative mt-0.5">
                    <input
                      type="text"
                      value={accountConfig.igUsername}
                      onChange={(e) => setAccountConfig(prev => ({ ...prev, igUsername: e.target.value }))}
                      placeholder="@your_username"
                      className="w-full bg-slate-900 border border-pink-500/40 rounded-lg px-2.5 py-1.5 text-xs text-pink-200 font-mono focus:outline-none focus:border-pink-400"
                    />
                  </div>
                </div>

                <div>
                  <label className="text-[10px] text-slate-400 font-mono">Instagram Password (Optional / For Direct Login)</label>
                  <div className="relative mt-0.5 flex items-center">
                    <input
                      type={showPassword ? "text" : "password"}
                      value={accountConfig.igPassword}
                      onChange={(e) => setAccountConfig(prev => ({ ...prev, igPassword: e.target.value }))}
                      placeholder="Enter account password"
                      className="w-full bg-slate-900 border border-pink-500/40 rounded-lg px-2.5 py-1.5 pr-8 text-xs text-pink-200 font-mono focus:outline-none focus:border-pink-400"
                    />
                    <button
                      type="button"
                      onClick={() => setShowPassword(!showPassword)}
                      className="absolute right-2 text-slate-400 hover:text-pink-300"
                    >
                      {showPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* WhatsApp Phone Number Configuration */}
            <div className="p-4 rounded-xl bg-emerald-950/20 border border-emerald-500/30 flex flex-col gap-3">
              <span className="text-xs font-bold text-emerald-300 uppercase tracking-wider flex items-center gap-1.5">
                <Smartphone className="w-3.5 h-3.5 text-emerald-400" />
                <span>WhatsApp Phone Number &amp; Line</span>
              </span>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5">
                <div>
                  <label className="text-[10px] text-slate-400 font-mono">My WhatsApp Phone Number</label>
                  <input
                    type="text"
                    value={accountConfig.senderNumber}
                    onChange={(e) => setAccountConfig(prev => ({ ...prev, senderNumber: e.target.value }))}
                    placeholder="+91 98200 12345"
                    className="w-full bg-slate-900 border border-emerald-500/40 rounded-lg px-2.5 py-1.5 text-xs text-emerald-200 font-mono focus:outline-none focus:border-emerald-400 mt-0.5"
                  />
                </div>

                <div>
                  <label className="text-[10px] text-slate-400 font-mono">Default Country Code</label>
                  <input
                    type="text"
                    value={accountConfig.countryCode}
                    onChange={(e) => setAccountConfig(prev => ({ ...prev, countryCode: e.target.value }))}
                    placeholder="+91 (India)"
                    className="w-full bg-slate-900 border border-emerald-500/40 rounded-lg px-2.5 py-1.5 text-xs text-emerald-200 font-mono focus:outline-none focus:border-emerald-400 mt-0.5"
                  />
                </div>
              </div>
            </div>

            {/* Mode-Specific Extras */}
            {accountConfig.igMethod === 'phone_link' && (
              <div className="p-3 rounded-xl bg-purple-950/20 border border-purple-500/30 flex items-center justify-between">
                <div className="flex items-center gap-2 text-xs text-purple-200">
                  <Smartphone className="w-4 h-4 text-purple-400" />
                  <span>Uses Instagram &amp; WhatsApp on connected Android phone (<span className="text-cyan-300 font-mono">192.168.29.159</span>)</span>
                </div>
                <button
                  type="button"
                  onClick={async () => {
                    showBanner('Testing Phone Link: Launching Instagram on phone...', 'info');
                    try {
                      await fetch('http://localhost:3001/api/social/send', {
                        method: 'POST',
                        headers: { 'Content-Type': 'application/json' },
                        body: JSON.stringify({
                          platform: 'instagram',
                          recipient: accountConfig.igUsername || '@jwalant',
                          recipientName: 'My Account Test',
                          message: '⚡ JASPER Assistant Phone Link Connection Test: OK!'
                        })
                      });
                      showBanner('Instagram Phone Link Test Triggered Successfully!', 'success');
                    } catch (e) {
                      showBanner('Test completed (virtual mode fallback ready).', 'info');
                    }
                  }}
                  className="px-2.5 py-1 rounded-lg bg-pink-600/30 hover:bg-pink-600/50 border border-pink-500/40 text-pink-200 text-xs font-mono font-bold"
                >
                  Test Link on Phone
                </button>
              </div>
            )}

            {accountConfig.igMethod === 'meta_graph' && (
              <div className="p-3 rounded-xl bg-pink-950/20 border border-pink-500/30 flex flex-col gap-2">
                <label className="text-[10px] text-slate-400 font-mono">Meta Graph Page Access Token</label>
                <input
                  type="password"
                  value={accountConfig.metaAccessToken}
                  onChange={(e) => setAccountConfig(prev => ({ ...prev, metaAccessToken: e.target.value }))}
                  placeholder="EAAG... (Paste token from developers.facebook.com)"
                  className="w-full bg-slate-900 border border-pink-500/30 rounded-lg px-2.5 py-1.5 text-xs text-pink-200 font-mono"
                />
              </div>
            )}

            {accountConfig.igMethod === 'session' && (
              <div className="p-3 rounded-xl bg-cyan-950/20 border border-cyan-500/30 flex flex-col gap-2">
                <label className="text-[10px] text-slate-400 font-mono">Instagram sessionid cookie</label>
                <input
                  type="password"
                  value={accountConfig.igSessionId}
                  onChange={(e) => setAccountConfig(prev => ({ ...prev, igSessionId: e.target.value }))}
                  placeholder="Paste your instagram.com sessionid cookie"
                  className="w-full bg-slate-900 border border-cyan-500/30 rounded-lg px-2.5 py-1.5 text-xs text-cyan-200 font-mono"
                />
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex items-center justify-end gap-2 pt-2 border-t border-purple-500/30">
              <button
                type="button"
                onClick={() => setShowAccountModal(false)}
                className="px-3 py-1.5 rounded-xl bg-slate-800 text-slate-300 hover:text-white text-xs font-mono transition-all"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={() => {
                  saveAccountsToServer(accountConfig);
                  setShowAccountModal(false);
                  showBanner(`Account details updated for ${accountConfig.igUsername} & ${accountConfig.senderNumber}!`, 'success');
                }}
                className="px-4 py-1.5 rounded-xl bg-gradient-to-r from-pink-500 to-purple-600 hover:from-pink-400 hover:to-purple-500 text-white font-bold text-xs font-mono transition-all shadow-[0_0_15px_rgba(236,72,153,0.3)] flex items-center gap-1.5"
              >
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>Save Account Credentials</span>
              </button>
            </div>

          </div>
        </div>
      )}

      {/* Add Contact Modal */}
      {showAddContactModal && (
        <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4">
          <div className="bg-slate-950 border border-cyan-500/50 rounded-2xl p-5 max-w-md w-full shadow-[0_0_40px_rgba(6,182,212,0.3)] flex flex-col gap-4 font-sans animate-in fade-in zoom-in duration-200">
            <div className="flex items-center justify-between border-b border-cyan-500/30 pb-3">
              <div className="flex items-center gap-2">
                <Users className="w-5 h-5 text-cyan-400" />
                <h3 className="font-orbitron font-bold text-sm text-cyan-200 uppercase tracking-wider">
                  Add Recent Contact
                </h3>
              </div>
              <button
                type="button"
                onClick={() => setShowAddContactModal(false)}
                className="text-slate-400 hover:text-white p-1"
              >
                ✕
              </button>
            </div>

            <div className="flex flex-col gap-3">
              <div>
                <label className="text-[10px] text-slate-400 font-mono">Contact Name</label>
                <input
                  type="text"
                  value={newContactForm.name}
                  onChange={(e) => setNewContactForm(prev => ({ ...prev, name: e.target.value }))}
                  placeholder="e.g. Alex (Mechanic) or Sarah"
                  className="w-full bg-slate-900 border border-cyan-500/40 rounded-lg px-2.5 py-1.5 text-xs text-cyan-200 font-mono mt-0.5 focus:outline-none focus:border-cyan-400"
                />
              </div>

              <div>
                <label className="text-[10px] text-slate-400 font-mono">Platform</label>
                <div className="grid grid-cols-2 gap-2 mt-0.5">
                  <button
                    type="button"
                    onClick={() => setNewContactForm(prev => ({ ...prev, platform: 'whatsapp' }))}
                    className={`py-1.5 rounded-lg border text-xs font-mono font-bold flex items-center justify-center gap-1.5 ${
                      newContactForm.platform === 'whatsapp'
                        ? 'bg-emerald-600/30 border-emerald-400 text-emerald-200'
                        : 'bg-slate-900 border-slate-800 text-slate-400'
                    }`}
                  >
                    <span>📱 WhatsApp</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => setNewContactForm(prev => ({ ...prev, platform: 'instagram' }))}
                    className={`py-1.5 rounded-lg border text-xs font-mono font-bold flex items-center justify-center gap-1.5 ${
                      newContactForm.platform === 'instagram'
                        ? 'bg-purple-600/30 border-purple-400 text-purple-200'
                        : 'bg-slate-900 border-slate-800 text-slate-400'
                    }`}
                  >
                    <span>📸 Instagram</span>
                  </button>
                </div>
              </div>

              {newContactForm.platform === 'whatsapp' ? (
                <div>
                  <label className="text-[10px] text-slate-400 font-mono">WhatsApp Phone Number</label>
                  <input
                    type="text"
                    value={newContactForm.phone}
                    onChange={(e) => setNewContactForm(prev => ({ ...prev, phone: e.target.value }))}
                    placeholder="+91 98200 00000"
                    className="w-full bg-slate-900 border border-emerald-500/40 rounded-lg px-2.5 py-1.5 text-xs text-emerald-200 font-mono mt-0.5 focus:outline-none focus:border-emerald-400"
                  />
                </div>
              ) : (
                <div>
                  <label className="text-[10px] text-slate-400 font-mono">Instagram Handle</label>
                  <input
                    type="text"
                    value={newContactForm.ig}
                    onChange={(e) => setNewContactForm(prev => ({ ...prev, ig: e.target.value }))}
                    placeholder="@username"
                    className="w-full bg-slate-900 border border-purple-500/40 rounded-lg px-2.5 py-1.5 text-xs text-purple-200 font-mono mt-0.5 focus:outline-none focus:border-purple-400"
                  />
                </div>
              )}
            </div>

            <div className="flex items-center justify-end gap-2 pt-2 border-t border-cyan-500/20">
              <button
                type="button"
                onClick={() => setShowAddContactModal(false)}
                className="px-3 py-1.5 rounded-xl bg-slate-800 text-slate-300 hover:text-white text-xs font-mono"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleAddContact}
                className="px-4 py-1.5 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-white font-bold text-xs font-mono shadow-md flex items-center gap-1.5"
              >
                <Plus className="w-3.5 h-3.5" />
                <span>Save Contact</span>
              </button>
            </div>
          </div>
        </div>
      )}

    </div>
  );
}
